# Match labelled rows with LLM-extracted rows
1. Load data
2. Vectorize rows
3. Match rows 
4. Compute accuracy

In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd
import geopy as gpy
import time
import itertools
import regex as re
from matplotlib import pyplot as plt
from src.data import *
from src.plot_functions import *
from src.post_process_functions import *
from src.geocoding import *
from src.hazard_def import *
from src.impact_def import *
from src.sanity_checks import *

## Load data

In [2]:
#load data (model)
post_processed = True #load or not post_processed data
model_name = "meta-llama/llama-4-scout-17b-16e-instruct"
nreports = 50
res_savename = f"post_processed_llm_response_impact_labelled_reports_{model_name.replace('/', '_')}.csv" if post_processed else f"llm_response_impact_labelled_reports_{model_name.replace('/', '_')}.csv"
extracted_df = pd.read_csv(DATA_OUT_LLMS+res_savename)

#load data (labelled)
res_savename = "post_processed_labelled_reports_impacts_all.csv" if post_processed else "labelled_reports_impacts_all.csv"
labelled_df = pd.read_csv(DATA_OUT_LLMS+res_savename)

FileNotFoundError: [Errno 2] No such file or directory: '../Data_backup/results_llm/post_processed_llm_response_impact_labelled_reports_meta-llama_llama-4-scout-17b-16e-instruct.csv'

In [ ]:
#reformat output
num_cols = ["impactValue"]#"startYear", "startMonth", "startDay", "endYear", "endMonth", "endDay"
list_cols = ["country","location", "hazards", "impactsAnnotation"]
labelled_df = format_output(labelled_df, num_cols=num_cols, list_cols=list_cols)
extracted_df = format_output(extracted_df, num_cols=num_cols, list_cols=list_cols)
#labelled_df.replace(np.nan, None, inplace=True)
#extracted_df.replace(np.nan, None, inplace=True)
combined_df = pd.concat([labelled_df, extracted_df])

In [ ]:
combined_df[combined_df["appealCode"]=="MDRSV012"]

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,impactsAnnotation,country,location,...,country_iso3_kw,hazards_reclass,impactValueOrig,impactUnitOrig,unit_type,country_kw,reportLink,disasterType,nathaz_text,impactType
106,2019-06-26,Affected People,NaN,people,NaN,NaN,NaN,[Situation analysis Description of the disaste...,[El Salvador],"[Morazn department, La Union department, El Br...",...,NaN,"['Tropical storm', 'Flood']",NaN,NaN,other,NaN,NaN,NaN,NaN,NaN
225,2019-06-26 00:00:00,Affected People,NaN,people,NaN,NaN,NaN,"[The rains have affected the entire country., ...",[El Salvador],"[eastern regions, San Miguel, La Unión departm...",...,SLV,"['Flood', 'Tropical storm']",NaN,people,other,El Salvador,https://adore.ifrc.org/Download.aspx?FileId=24...,Flood,['The major donors and partners of the Disaste...,NaN
226,2019-06-26 00:00:00,Other Infrastructure Impacts,NaN,unknown,NaN,NaN,NaN,"[The rains have affected the entire country., ...",[El Salvador],"[eastern regions, San Miguel, La Unión departm...",...,SLV,"['Flood', 'Tropical storm']",NaN,NaN,other,El Salvador,https://adore.ifrc.org/Download.aspx?FileId=24...,Flood,['The major donors and partners of the Disaste...,NaN
227,2019-06-26 00:00:00,"Water, Sanitation, and Hygiene Infrastructure",NaN,undefined WASH facilities,NaN,NaN,NaN,"[The rains have affected the entire country., ...",[El Salvador],"[eastern regions, San Miguel, La Unión departm...",...,SLV,"['Flood', 'Tropical storm']",NaN,NaN,other,El Salvador,https://adore.ifrc.org/Download.aspx?FileId=24...,Flood,['The major donors and partners of the Disaste...,NaN

## Match
1. Vectorize columns that need to be compared using cosine similarity
2. Compute cosine similarity for those columns for each possible extracted-labelled pair
3. Add absolute difference of impactValue between each possible extracted-labelled pair.
    Need to consider NaN from not NaN separately. Only try matching non-NaNs with non-NaNs 
    (and nans with nan?)
4. Compute Intersection-Over-Union of polygons for each possible pair
5. Match by maximizing similarity and -impactvalu_idff and -IoT. Allow for more than one match.

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

def vectorize(cell_values, unique_values):
    """vectorizing function for categorical columns"""
    #cell_values = list() if not cell_values else cell_values
    cell_values = [cell_values] if not isinstance(cell_values, list) else cell_values
    vector = [1 if unique_value in cell_values else 0 for unique_value in unique_values]
    return np.array(vector)

def make_cosine_matrix():
    return

def split_nans(df,key):
    return df[~df[key].isna()], df[df[key].isna()]




unique_countries_ISO = [country.alpha_3 for country in pycountry.countries]
unique_country_names = [country.name for country in pycountry.countries]
pattern = '|'.join(map(re.escape, unique_country_names))

unique_dict = {#mapping dictonary
    'hazards' : hazard_main_types_emdat_extended,
    'country' : unique_country_names,
    'startYear' : np.arange(1980, 2025).tolist(),
    'startMonth' : np.arange(1, 13).tolist(),
    'startDay' : np.arange(1, 32).tolist(),
    'endYear' : np.arange(1980, 2025).tolist(),
    'endMonth' : np.arange(1, 13).tolist(),
    'endDay' : np.arange(1, 32).tolist(),
    'impactSubtype' : impactSubtype_list,
    'impactUnit' : combined_df.impactUnit.unique().tolist()
}

match_idxs = {}
for appeal, ext_group in extracted_df.groupby("appealCode"):
    matching_cols = list(unique_dict.keys())
    lab_group = labelled_df[labelled_df["appealCode"] == appeal]

    if lab_group.shape[0] == 0:
        continue

    ext_vect_df = pd.DataFrame(columns=matching_cols)
    lab_vect_df = pd.DataFrame(columns=matching_cols)

    #vectorize
    for col in matching_cols:
        ext_vect_df[col] = ext_group[col].apply(vectorize, unique_values=unique_dict[col])
        lab_vect_df[col] = lab_group[col].apply(vectorize, unique_values=unique_dict[col])

    #compute cosine distance
    matching_cols = matching_cols# + ["impactValue"]

    dist_mat = np.full((len(ext_vect_df), len(lab_vect_df), len(matching_cols)), np.nan)
    for k, col in enumerate(matching_cols):
        if col == "impactValue":
            pass
            # add negative absolute diff for impact value
            # dist must be negative as we want to maximize similarity
            #dist_mat[:,:,k] = -np.abs(ext_group["impactValue"].values.reshape(-1, 1) - lab_group["impactValue"].values.reshape(1, -1))
        else: #compute cosine similarity
            # Convert Series of arrays/lists to 2D numpy arrays
            X = np.stack(ext_vect_df[col].values) #nsamples, nfeatures
            Y = np.stack(lab_vect_df[col].values)
            # Compute cosine similarity
            dist_mat[:,:,k] = cosine_similarity(X, Y)

    #need to separate Nans from not Nans
    not_nan_ext_df, nan_ext_df = split_nans(ext_group,"impactValue")
    not_nan_lab_df, nan_lab_df = split_nans(lab_group,"impactValue")

    #retrieve positional indices
    nan_id_ext = nan_ext_df.reset_index().index.values
    nan_id_lab = nan_lab_df.reset_index().index.values
    not_nan_id_ext = not_nan_ext_df.reset_index().index.values
    not_nan_id_lab = not_nan_lab_df.reset_index().index.values

    #remove nans from dist matrix
    if len(nan_id_ext):
        if len(nan_id_lab):
            dist_mat_notna = np.delete(np.delete(dist_mat, nan_id_ext, axis=0), nan_id_lab, axis=1)
            dist_mat_na = dist_mat[nan_id_ext, :, :][:,nan_id_lab,:]
        else:
            dist_mat_notna = np.delete(dist_mat, nan_id_ext, axis=0)
            dist_mat_na = dist_mat[nan_id_ext, :, :]
    else:
        if len(nan_id_lab):
            dist_mat_notna = np.delete(dist_mat, nan_id_lab, axis=1)
            dist_mat_na = None
        else:
            dist_mat_notna = dist_mat
            dist_mat_na = None

    #calculate diff
    value_diff = -np.abs(not_nan_ext_df["impactValue"].values.reshape(-1, 1) - not_nan_lab_df["impactValue"].values.reshape(1, -1))
    dist_mat_notna = np.append(dist_mat_notna, value_diff[:,:, None], axis=2)

    ## TODO ADD IOTs

    #find possible candidates based on max similarity
    agg_sim_notna = np.nansum(dist_mat_notna, axis=2) #aggregate score for all matching columns (#ext, #lab)
    print(appeal)
    print(agg_sim_notna)
    max_sim_notna = np.max(agg_sim_notna, axis=1) #find max similarity value (#ext)
    id_match_ext_notna, id_match_lab_notna = np.where(agg_sim_notna == max_sim_notna[:,None]) #possible candidates with max similarity

    #reindex back in original df
    id_match_ext = not_nan_ext_df.iloc[id_match_ext_notna].index.values.flatten()
    id_match_lab = not_nan_lab_df.iloc[id_match_lab_notna].index.values.flatten()

    #find possible candidates based on max similarity
    if dist_mat_na is not None:
        agg_sim_na = np.nansum(dist_mat_na, axis=2) #aggregate score for all matching columns (#ext, #lab)
        max_sim_na = np.max(agg_sim_na, axis=1) #find max similarity value (#ext)
        id_match_ext_na, id_match_lab_na = np.where(agg_sim_na == max_sim_na[:,None]) #possible candidates with max similarity
        id_match_ext_na = nan_ext_df.iloc[id_match_ext_na].index.values.flatten()
        id_match_lab_na = nan_lab_df.iloc[id_match_lab_na].index.values.flatten()
        id_match_ext = np.append(id_match_ext, id_match_ext_na)
        id_match_lab = np.append(id_match_lab, id_match_lab_na)
    #write as df
    match_table = pd.DataFrame((id_match_ext, id_match_lab),
                               index = ["ext_match_id", "lab_match_id"]).T

    ##find possible candidates based on max similarity
    #agg_sim = np.nansum(dist_mat, axis=2) #aggregate score for all matching columns (#ext, #lab)
    #max_sim = np.max(agg_sim, axis=1) #find max similarity value (#ext)
    #id_match_ext, id_match_lab = np.where(agg_sim == max_sim[:,None]) #possible candidates with max similarity
    #
    #match_table = pd.DataFrame((id_match_ext, ext_group.iloc[id_match_ext].impactValue.values,
    #                           id_match_lab, lab_group.iloc[id_match_lab].impactValue.values),
    #                           index = ["ext_id", "ext_impactValue", "lab_id", "lab_impactValue"]).T
    #
    #for ext_id, group in match_table.groupby("ext_id"):
    #    value_diff = np.abs(group["lab_impactValue"] - group["ext_impactValue"] )
    #    if not pd.isna(group["ext_impactValue"]):
    #        #if value is not NaN, only match with numbers
    #        match_idxs[ext_id] = value_diff.dropna(how="any").min().lab_id
    #    else:
    #        #if value is NaN, only match with NaNs?
    #        match_idxs[ext_id] = group.where(group["lab_impactValue"].isna()).lab_id

MDRBD022
[[-5.42347600e+06 -6.59999700e+06 -5.49999700e+06 -7.58999700e+06
  -7.59984767e+06 -5.42347800e+06 -7.59600900e+06 -7.50142500e+06
  -7.56817900e+06 -7.59984967e+06]
 [-1.87651500e+06 -6.99997000e+05 -1.79999700e+06 -2.89997000e+05
  -2.99848670e+05 -1.87651600e+06 -2.96009000e+05 -2.01424000e+05
  -2.68179000e+05 -2.99849670e+05]
 [-2.17640100e+06 -9.99883000e+05 -2.09988300e+06 -9.88300000e+03
  -2.93300000e+01 -2.17640200e+06 -3.87100000e+03 -9.84530000e+04
  -3.17010000e+04 -3.03300000e+01]
 [-1.57651600e+06 -3.99995000e+05 -1.49999700e+06 -5.89997000e+05
  -5.99849670e+05 -1.57651400e+06 -5.96007000e+05 -5.01426000e+05
  -5.68179000e+05 -5.99849670e+05]
 [-2.17119600e+06 -9.94677000e+05 -2.09467500e+06 -4.67700000e+03
  -5.16967000e+03 -2.17119600e+06 -1.32900000e+03 -9.32480000e+04
  -2.64930000e+04 -5.16967000e+03]
 [-2.13651400e+06 -9.59997000e+05 -2.05999700e+06 -2.99970000e+04
  -3.98476700e+04 -2.13651600e+06 -3.60090000e+04 -5.85670000e+04
  -8.17900000e+03 -3.98496700e+04]
 [-2.17625000e+06 -9.99732000e+05 -2.09973200e+06 -9.73200000e+03
  -1.15670000e+02 -2.17625100e+06 -3.72000000e+03 -9.83020000e+04
  -3.15500000e+04 -1.16670000e+02]
 [-2.17636800e+06 -9.99850000e+05 -2.09985000e+06 -9.85000000e+03
   2.33000000e+00 -2.17636900e+06 -3.83800000e+03 -9.84200000e+04
  -3.16680000e+04  1.33000000e+00]
 [-3.22347700e+06 -4.39999800e+06 -3.29999800e+06 -5.38999800e+06
  -5.39984867e+06 -3.22347900e+06 -5.39601000e+06 -5.30142600e+06
  -5.36818000e+06 -5.39985067e+06]
 [-1.97115000e+06 -7.94629000e+05 -1.89463100e+06 -1.95367000e+05
  -2.05219670e+05 -1.97114800e+06 -2.01377000e+05 -1.06796000e+05
  -1.73549000e+05 -2.05219670e+05]
 [-4.23478000e+05 -1.59999900e+06 -4.99999000e+05 -2.58999900e+06
  -2.59984967e+06 -4.23480000e+05 -2.59601100e+06 -2.50142700e+06
  -2.56818100e+06 -2.59985167e+06]]
MDRBJ019
[[ 4.000000e+00 -3.156500e+04 -3.036900e+04 -3.401019e+04 -2.985200e+04
  -3.036900e+04]
 [-2.383300e+04 -7.729000e+03 -6.532000e+03 -1.017319e+04 -6.015000e+03
  -6.532000e+03]]
MDRCM039
[[-3.4137600e+05 -4.2499600e+05 -4.5699600e+05 -4.9099600e+05
  -4.8199600e+05 -4.8699600e+05 -4.9959700e+05 -4.9979700e+05
  -4.9130700e+05 -4.8981900e+05 -4.9996702e+05 -4.6399600e+05
  -4.8999600e+05]
 [-1.5857900e+05 -7.4959000e+04 -4.2959000e+04 -8.9590000e+03
  -1.7959000e+04 -1.2959000e+04 -3.5700000e+02 -1.5900000e+02
  -8.6490000e+03 -1.0137000e+04 -5.0200000e+00 -3.5959000e+04
  -9.9590000e+03]
 [-1.5860900e+05 -7.4989000e+04 -4.2989000e+04 -8.9890000e+03
  -1.7989000e+04 -1.2989000e+04 -3.8900000e+02 -1.8700000e+02
  -8.6790000e+03 -1.0167000e+04 -1.8980000e+01 -3.5989000e+04
  -9.9890000e+03]
 [-1.0253300e+05 -1.8913000e+04 -1.3081000e+04 -4.7081000e+04
  -3.8081000e+04 -4.3081000e+04 -5.5681000e+04 -5.5881000e+04
  -4.7390000e+04 -4.5903000e+04 -5.6051020e+04 -2.0081000e+04
  -4.6081000e+04]
 [-1.5310700e+05 -6.9487000e+04 -3.7487000e+04 -3.4870000e+03
  -1.2487000e+04 -7.4870000e+03 -5.1070000e+03 -5.3070000e+03
  -3.1770000e+03 -4.6650000e+03 -5.4770200e+03 -3.0487000e+04
  -4.4870000e+03]
 [-1.5776347e+05 -7.4143470e+04 -4.2143470e+04 -8.1434700e+03
  -1.7143470e+04 -1.2143470e+04 -4.4953000e+02 -6.4953000e+02
  -7.8344700e+03 -9.3224700e+03 -8.1955000e+02 -3.5143470e+04
  -9.1434700e+03]
 [-1.5835400e+05 -7.4734000e+04 -4.2734000e+04 -8.7340000e+03
  -1.7734000e+04 -1.2734000e+04 -1.3500000e+02 -6.1000000e+01
  -8.4250000e+03 -9.9130000e+03 -2.3102000e+02 -3.5734000e+04
  -9.7340000e+03]
 [-5.4711000e+04 -2.8903000e+04 -6.0903000e+04 -9.4903000e+04
  -8.5903000e+04 -9.0903000e+04 -1.0350400e+05 -1.0370400e+05
  -9.5214000e+04 -9.3726000e+04 -1.0387402e+05 -6.7903000e+04
  -9.3903000e+04]
 [-1.5858600e+05 -7.4966000e+04 -4.2966000e+04 -8.9660000e+03
  -1.7966000e+04 -1.2966000e+04 -3.6600000e+02 -1.6600000e+02
  -8.6560000e+03 -1.0144000e+04 -2.0000000e-02 -3.5966000e+04
  -9.9660000e+03]
 [-1.5861600e+05 -7.4996000e+04 -4.2996000e+04 -8.9960000e+03
  -1.7996000e+04 -1.2996000e+04 -3.9700000e+02 -1.9700000e+02
  -8.6870000e+03 -1.0175000e+04 -2.6980000e+01 -3.5996000e+04
  -9.9960000e+03]]
MDRCN006
[[ 5.00000000e+00 -1.38099200e+06 -1.15899500e+06 -1.35899600e+06
  -1.38009600e+06 -1.35199600e+06 -1.38062700e+06 -7.90618994e+08
  -1.37995000e+05 -1.38098300e+06 -1.38099100e+06 -1.35099600e+06
  -1.37869600e+06 -1.36199600e+06 -5.36618996e+08]
 [-1.38099100e+06  5.00000000e+00 -2.21992000e+05 -2.19930000e+04
  -8.93000000e+02 -2.89930000e+04 -3.62000000e+02 -7.91999992e+08
  -1.51899100e+06 -4.00000000e+00  4.00000000e+00 -2.99930000e+04
  -2.29300000e+03 -1.89930000e+04 -5.37999993e+08]
 [-1.15899500e+06 -2.21991000e+05  5.00000000e+00 -1.99996000e+05
  -2.21096000e+05 -1.92996000e+05 -2.21627000e+05 -7.91777995e+08
  -1.29699500e+06 -2.21983000e+05 -2.21990000e+05 -1.91996000e+05
  -2.19696000e+05 -2.02996000e+05 -5.37777996e+08]
 [-1.38009600e+06 -8.93000000e+02 -2.21096000e+05 -2.10950000e+04
   5.00000000e+00 -2.80960000e+04 -5.27000000e+02 -7.91999096e+08
  -1.51809600e+06 -8.84000000e+02 -8.92000000e+02 -2.90950000e+04
  -1.39500000e+03 -1.80960000e+04 -5.37999095e+08]
 [-1.35199600e+06 -2.89930000e+04 -1.92996000e+05 -6.99400000e+03
  -2.80940000e+04  4.00000000e+00 -2.86270000e+04 -7.91970996e+08
  -1.48999600e+06 -2.89840000e+04 -2.89920000e+04 -9.94000000e+02
  -2.66940000e+04 -9.99500000e+03 -5.37970994e+08]
 [-1.38062700e+06 -3.62000000e+02 -2.21627000e+05 -2.16270000e+04
  -5.27000000e+02 -2.86260000e+04  5.00000000e+00 -7.91999627e+08
  -1.51862700e+06 -3.53000000e+02 -3.61000000e+02 -2.96270000e+04
  -1.92700000e+03 -1.86270000e+04 -5.37999627e+08]
 [-1.38099070e+06  1.70000000e+00 -2.21990700e+05 -2.19907000e+04
  -8.90700000e+02 -2.89907000e+04 -3.59700000e+02 -7.91999991e+08
  -1.51899070e+06 -2.70000000e+00  2.70000000e+00 -2.99907000e+04
  -2.29070000e+03 -1.89907000e+04 -5.37999991e+08]
 [-1.37996000e+05 -1.51899300e+06 -1.29699600e+06 -1.49699700e+06
  -1.51809700e+06 -1.48999700e+06 -1.51862800e+06 -7.90480995e+08
   4.00000000e+00 -1.51898400e+06 -1.51899200e+06 -1.48899700e+06
  -1.51669700e+06 -1.49999700e+06 -5.36480997e+08]
 [-1.38098300e+06 -5.00000000e+00 -2.21984000e+05 -2.19850000e+04
  -8.85000000e+02 -2.89850000e+04 -3.54000000e+02 -7.91999984e+08
  -1.51898300e+06  4.00000000e+00 -4.00000000e+00 -2.99850000e+04
  -2.28500000e+03 -1.89850000e+04 -5.37999985e+08]
 [-1.38099200e+06  3.00000000e+00 -2.21992000e+05 -2.19930000e+04
  -8.93000000e+02 -2.89930000e+04 -3.62000000e+02 -7.91999992e+08
  -1.51899200e+06 -3.00000000e+00  4.00000000e+00 -2.99930000e+04
  -2.29300000e+03 -1.89930000e+04 -5.37999993e+08]
 [-1.35099600e+06 -2.99920000e+04 -1.91996000e+05 -7.99700000e+03
  -2.90970000e+04 -9.97000000e+02 -2.96280000e+04 -7.91969996e+08
  -1.48899600e+06 -2.99840000e+04 -2.99910000e+04  3.00000000e+00
  -2.76970000e+04 -1.09970000e+04 -5.37969997e+08]
 [-1.37869700e+06 -2.29400000e+03 -2.19697000e+05 -1.96960000e+04
  -1.39600000e+03 -2.66970000e+04 -1.92800000e+03 -7.91997697e+08
  -1.51669700e+06 -2.28500000e+03 -2.29300000e+03 -2.76960000e+04
   4.00000000e+00 -1.66970000e+04 -5.37997696e+08]
 [-1.36199700e+06 -1.89940000e+04 -2.02997000e+05 -2.99500000e+03
  -1.80950000e+04 -9.99700000e+03 -1.86280000e+04 -7.91980997e+08
  -1.49999700e+06 -1.89850000e+04 -1.89930000e+04 -1.09950000e+04
  -1.66950000e+04  4.00000000e+00 -5.37980995e+08]
 [-1.38099340e+06  2.40000000e+00 -2.21993400e+05 -2.19934000e+04
  -8.93400000e+02 -2.89934000e+04 -3.62400000e+02 -7.91999993e+08
  -1.51899340e+06 -5.40000000e+00  2.60000000e+00 -2.99934000e+04
  -2.29340000e+03 -1.89934000e+04 -5.37999993e+08]]
MDRIQ014
[[-7.483e+03  3.000e+00 -6.983e+03]
 [ 2.000e+00 -7.484e+03 -4.980e+02]]
MDRKE058
[[-6.39790000e+04 -1.05242000e+05 -1.39061293e+05 -1.39050293e+05
  -1.38988293e+05 -1.35666293e+05 -1.38960047e+05 -1.08054293e+05
  -1.38891293e+05 -1.38827293e+05 -1.38069293e+05 -2.78080293e+05
  -5.44752929e+04 -1.38826293e+05 -1.39041293e+05 -1.38890293e+05
  -1.39030293e+05 -5.44832929e+04 -1.05243293e+05 -2.78138293e+05
  -6.39772929e+04 -1.39010293e+05 -1.39062293e+05 -1.39040293e+05
  -1.39045293e+05 -1.21677293e+05 -1.34245293e+05 -1.11352293e+05
  -1.37769293e+05 -1.38805293e+05 -1.39035293e+05 -1.39046293e+05
  -1.39060293e+05 -1.38739293e+05 -1.39019293e+05 -1.39039293e+05
  -1.39067293e+05 -1.39067293e+05 -1.39064293e+05]
 [-1.18456000e+05 -1.59720000e+05 -1.93538293e+05 -1.93527293e+05
  -1.93464293e+05 -1.90144293e+05 -1.93436047e+05 -1.62531293e+05
  -1.93368293e+05 -1.93304293e+05 -1.92546293e+05 -2.23603293e+05
   1.70710678e+00 -1.93303293e+05 -1.93518293e+05 -1.93367293e+05
  -1.93507293e+05 -5.29289322e+00 -1.59719293e+05 -2.23662293e+05
  -1.18455293e+05 -1.93487293e+05 -1.93539293e+05 -1.93517293e+05
  -1.93522293e+05 -1.76154293e+05 -1.88722293e+05 -1.65829293e+05
  -1.92246293e+05 -1.93282293e+05 -1.93512293e+05 -1.93523293e+05
  -1.93537293e+05 -1.93216293e+05 -1.93496293e+05 -1.93516293e+05
  -1.93544293e+05 -1.93544293e+05 -1.93541293e+05]
 [-7.49100000e+04 -3.36440000e+04 -1.66292893e+02 -1.56292893e+02
  -9.42928932e+01 -3.21929289e+03 -6.60471446e+01 -3.08342929e+04
   2.70710678e+00 -6.12928932e+01 -8.19292893e+02 -4.16972293e+05
  -1.93367293e+05 -6.02928932e+01 -1.48292893e+02  4.70710678e+00
  -1.36292893e+02 -1.93375293e+05 -3.36442929e+04 -4.17031293e+05
  -7.49092929e+04 -1.16292893e+02 -1.69292893e+02 -1.46292893e+02
  -1.52292893e+02 -1.72112929e+04 -4.64429289e+03 -2.75372929e+04
  -1.11929289e+03 -8.42928932e+01 -1.42292893e+02 -1.53292893e+02
  -1.67292893e+02 -1.48292893e+02 -1.26292893e+02 -1.46292893e+02
  -1.74292893e+02 -1.74292893e+02 -1.70292893e+02]
 [-7.48460000e+04 -3.35800000e+04 -2.31292893e+02 -2.19292893e+02
  -1.58292893e+02 -3.15529289e+03 -1.30047145e+02 -3.07702929e+04
  -6.12928932e+01  2.70710678e+00 -7.55292893e+02 -4.16908293e+05
  -1.93303293e+05  4.70710678e+00 -2.11292893e+02 -6.02928932e+01
  -2.01292893e+02 -1.93311293e+05 -3.35802929e+04 -4.16967293e+05
  -7.48452929e+04 -1.80292893e+02 -2.33292893e+02 -2.10292893e+02
  -2.16292893e+02 -1.71472929e+04 -4.58029289e+03 -2.74732929e+04
  -1.05529289e+03 -2.02928932e+01 -2.06292893e+02 -2.17292893e+02
  -2.31292893e+02 -8.42928932e+01 -1.90292893e+02 -2.10292893e+02
  -2.38292893e+02 -2.38292893e+02 -2.35292893e+02]
 [-4.40730000e+04 -2.80600000e+03 -3.10052929e+04 -3.09942929e+04
  -3.09322929e+04 -2.76102929e+04 -3.09040471e+04  1.70710678e+00
  -3.08352929e+04 -3.07712929e+04 -3.00132929e+04 -3.86136293e+05
  -1.62531293e+05 -3.07702929e+04 -3.09852929e+04 -3.08342929e+04
  -3.09742929e+04 -1.62539293e+05 -2.80729289e+03 -3.86194293e+05
  -4.40712929e+04 -3.09542929e+04 -3.10062929e+04 -3.09842929e+04
  -3.09892929e+04 -1.36212929e+04 -2.61892929e+04 -3.29629289e+03
  -2.97132929e+04 -3.07492929e+04 -3.09792929e+04 -3.09902929e+04
  -3.10042929e+04 -3.06832929e+04 -3.09632929e+04 -3.09832929e+04
  -3.10112929e+04 -3.10112929e+04 -3.10082929e+04]
 [-4.12630000e+04  3.00000000e+00 -3.38152929e+04 -3.38042929e+04
  -3.37412929e+04 -3.04212929e+04 -3.37130471e+04 -2.80829289e+03
  -3.36452929e+04 -3.35812929e+04 -3.28232929e+04 -3.83326293e+05
  -1.59721293e+05 -3.35802929e+04 -3.37952929e+04 -3.36442929e+04
  -3.37842929e+04 -1.59728293e+05  3.70710678e+00 -3.83385293e+05
  -4.12622929e+04 -3.37642929e+04 -3.38162929e+04 -3.37942929e+04
  -3.37992929e+04 -1.64312929e+04 -2.89992929e+04 -6.10629289e+03
  -3.25232929e+04 -3.35592929e+04 -3.37892929e+04 -3.38002929e+04
  -3.38142929e+04 -3.34932929e+04 -3.37732929e+04 -3.37932929e+04
  -3.38212929e+04 -3.38212929e+04 -3.38182929e+04]
 [ 2.00000000e+00 -4.12610000e+04 -7.50802929e+04 -7.50692929e+04
  -7.50072929e+04 -7.16852929e+04 -7.49790471e+04 -4.40732929e+04
  -7.49102929e+04 -7.48462929e+04 -7.40882929e+04 -3.42061293e+05
  -1.18456293e+05 -7.48452929e+04 -7.50602929e+04 -7.49092929e+04
  -7.50492929e+04 -1.18464293e+05 -4.12622929e+04 -3.42119293e+05
   3.70710678e+00 -7.50292929e+04 -7.50812929e+04 -7.50592929e+04
  -7.50642929e+04 -5.76962929e+04 -7.02642929e+04 -4.73712929e+04
  -7.37882929e+04 -7.48242929e+04 -7.50542929e+04 -7.50652929e+04
  -7.50792929e+04 -7.47582929e+04 -7.50382929e+04 -7.50582929e+04
  -7.50862929e+04 -7.50862929e+04 -7.50832929e+04]
 [-7.50810000e+04 -3.38160000e+04  1.70710678e+00 -9.29289322e+00
  -7.12928932e+01 -3.39229289e+03 -9.95386418e+01 -3.10062929e+04
  -1.68292893e+02 -2.33292893e+02 -9.91292893e+02 -4.17144293e+05
  -1.93539293e+05 -2.33292893e+02 -1.82928932e+01 -1.69292893e+02
  -2.92928932e+01 -1.93548293e+05 -3.38162929e+04 -4.17204293e+05
  -7.50812929e+04 -4.82928932e+01  3.70710678e+00 -2.02928932e+01
  -1.52928932e+01 -1.73832929e+04 -4.81529289e+03 -2.77082929e+04
  -1.29129289e+03 -2.55292893e+02 -2.42928932e+01 -1.32928932e+01
   7.07106781e-01 -3.20292893e+02 -4.02928932e+01 -2.02928932e+01
  -4.29289322e+00 -4.29289322e+00 -1.29289322e+00]
 [-7.50700000e+04 -3.38050000e+04 -9.29289322e+00  1.70710678e+00
  -6.02928932e+01 -3.38129289e+03 -8.85386418e+01 -3.09952929e+04
  -1.58292893e+02 -2.21292893e+02 -9.80292893e+02 -4.17133293e+05
  -1.93528293e+05 -2.22292893e+02 -7.29289322e+00 -1.58292893e+02
  -1.82928932e+01 -1.93537293e+05 -3.38052929e+04 -4.17193293e+05
  -7.50702929e+04 -3.92928932e+01 -9.29289322e+00 -7.29289322e+00
  -2.29289322e+00 -1.73722929e+04 -4.80429289e+03 -2.76972929e+04
  -1.28029289e+03 -2.44292893e+02 -1.32928932e+01 -2.29289322e+00
  -8.29289322e+00 -3.09292893e+02 -2.92928932e+01 -9.29289322e+00
  -1.52928932e+01 -1.52928932e+01 -1.22928932e+01]
 [-7.16870000e+04 -3.04220000e+04 -3.39229289e+03 -3.38129289e+03
  -3.31929289e+03  1.70710678e+00 -3.29104714e+03 -2.76122929e+04
  -3.22129289e+03 -3.15729289e+03 -2.39829289e+03 -4.13750293e+05
  -1.90145293e+05 -3.15729289e+03 -3.37229289e+03 -3.22129289e+03
  -3.36129289e+03 -1.90154293e+05 -3.04222929e+04 -4.13810293e+05
  -7.16872929e+04 -3.34029289e+03 -3.39229289e+03 -3.37029289e+03
  -3.37529289e+03 -1.39872929e+04 -1.41929289e+03 -2.43142929e+04
  -2.09929289e+03 -3.13529289e+03 -3.36629289e+03 -3.37729289e+03
  -3.39129289e+03 -3.07029289e+03 -3.35029289e+03 -3.37029289e+03
  -3.39829289e+03 -3.39829289e+03 -3.39529289e+03]
 [-7.49787543e+04 -3.37147543e+04 -9.95386418e+01 -8.85386418e+01
  -2.65386418e+01 -3.29104714e+03  1.70710678e+00 -3.09050471e+04
  -6.80471446e+01 -1.32047145e+02 -8.90047145e+02 -4.17042047e+05
  -1.93438047e+05 -1.32047145e+02 -7.95386418e+01 -6.80471446e+01
  -6.85386418e+01 -1.93447047e+05 -3.37150471e+04 -4.17103047e+05
  -7.49800471e+04 -4.75386418e+01 -9.95386418e+01 -7.75386418e+01
  -8.25386418e+01 -1.72820471e+04 -4.71404714e+03 -2.76060471e+04
  -1.19004714e+03 -1.54047145e+02 -7.35386418e+01 -8.45386418e+01
  -9.85386418e+01 -2.19047145e+02 -5.75386418e+01 -7.75386418e+01
  -1.05538642e+02 -1.05538642e+02 -1.02538642e+02]
 [-7.50260000e+04 -3.37600000e+04 -5.40000000e+01 -4.30000000e+01
  -1.50000000e+01 -3.33600000e+03 -4.32457486e+01 -3.09510000e+04
  -1.14000000e+02 -1.78000000e+02 -9.36000000e+02 -4.17089000e+05
  -1.93484000e+05 -1.77000000e+02 -3.40000000e+01 -1.13000000e+02
  -2.30000000e+01 -1.93492000e+05 -3.37600000e+04 -4.17148000e+05
  -7.50250000e+04 -3.00000000e+00 -5.50000000e+01 -3.30000000e+01
  -3.80000000e+01 -1.73280000e+04 -4.76000000e+03 -2.76530000e+04
  -1.23600000e+03 -2.00000000e+02 -2.62928932e+01 -3.72928932e+01
  -5.12928932e+01 -2.62292893e+02 -1.02928932e+01 -3.02928932e+01
  -5.82928932e+01 -5.82928932e+01 -5.62928932e+01]
 [-7.46800000e+04 -3.34140000e+04 -4.00000000e+02 -3.89000000e+02
  -3.27000000e+02 -2.99000000e+03 -2.98754251e+02 -3.06050000e+04
  -2.30000000e+02 -1.66000000e+02 -5.90000000e+02 -4.16743000e+05
  -1.93138000e+05 -1.65000000e+02 -3.80000000e+02 -2.29000000e+02
  -3.69000000e+02 -1.93146000e+05 -3.34140000e+04 -4.16802000e+05
  -7.46790000e+04 -3.49000000e+02 -4.01000000e+02 -3.79000000e+02
  -3.84000000e+02 -1.69820000e+04 -4.41400000e+03 -2.73070000e+04
  -8.90000000e+02 -1.44000000e+02 -3.72292893e+02 -3.83292893e+02
  -3.97292893e+02 -7.62928932e+01 -3.56292893e+02 -3.76292893e+02
  -4.04292893e+02 -4.04292893e+02 -4.02292893e+02]]
MDRMY003
[[ 6.0000e+00 -1.4994e+04 -2.2994e+04]
 [-2.2994e+04 -7.9940e+03  6.0000e+00]
 [-1.4994e+04  6.0000e+00 -7.9940e+03]]
MDRNG041
[[-4.979800e+04 -7.980000e+02 -1.462000e+03 -5.798000e+03 -1.950000e+02
  -9.700000e+01 -1.970000e+02 -1.360000e+02 -1.100000e+01 -5.400000e+01
  -1.650000e+02 -1.590000e+02 -1.300000e+02]
 [-4.949800e+04 -4.980000e+02 -1.162000e+03 -5.498000e+03 -4.950000e+02
  -1.970000e+02 -9.700000e+01 -4.360000e+02 -2.850000e+02 -3.540000e+02
  -4.650000e+02 -4.590000e+02 -4.300000e+02]
 [-4.697000e+04 -2.026000e+03 -1.362000e+03 -2.970000e+03 -3.023000e+03
  -2.725000e+03 -2.625000e+03 -2.964000e+03 -2.813000e+03 -2.882000e+03
  -2.993000e+03 -2.987000e+03 -2.958000e+03]
 [-4.697800e+04 -2.016000e+03 -1.352000e+03 -2.980000e+03 -3.011000e+03
  -2.716000e+03 -2.616000e+03 -2.952000e+03 -2.801000e+03 -2.870000e+03
  -2.983000e+03 -2.978000e+03 -2.948000e+03]
 [-4.880800e+04 -1.880000e+02 -4.720000e+02 -4.808000e+03 -1.185000e+03
  -8.880000e+02 -7.880000e+02 -1.126000e+03 -9.750000e+02 -1.044000e+03
  -1.155000e+03 -1.150000e+03 -1.118000e+03]
 [-1.296409e+06 -1.345409e+06 -1.344745e+06 -1.340409e+06 -1.346406e+06
  -1.346107e+06 -1.346007e+06 -1.346347e+06 -1.346196e+06 -1.346265e+06
  -1.346376e+06 -1.346370e+06 -1.346341e+06]
 [-6.793060e+05 -7.283060e+05 -7.276420e+05 -7.233060e+05 -7.293030e+05
  -7.290050e+05 -7.289050e+05 -7.292440e+05 -7.290930e+05 -7.291620e+05
  -7.292730e+05 -7.292670e+05 -7.292380e+05]
 [-4.714200e+04 -1.850000e+03 -1.186000e+03 -3.142000e+03 -2.847000e+03
  -2.549000e+03 -2.449000e+03 -2.788000e+03 -2.637000e+03 -2.706000e+03
  -2.817000e+03 -2.811000e+03 -2.782000e+03]
 [-4.967600e+04 -6.760000e+02 -1.340000e+03 -5.676000e+03 -3.130000e+02
  -1.500000e+01 -7.500000e+01 -2.540000e+02 -1.030000e+02 -1.720000e+02
  -2.830000e+02 -2.770000e+02 -2.480000e+02]
 [-6.968400e+04 -1.186860e+05 -1.180220e+05 -1.136860e+05 -1.196810e+05
  -1.193860e+05 -1.192860e+05 -1.196220e+05 -1.194710e+05 -1.195400e+05
  -1.196530e+05 -1.196480e+05 -1.196180e+05]
 [-4.804963e+04 -9.423700e+02 -2.773700e+02 -4.048630e+03 -1.939370e+03
  -1.642370e+03 -1.542370e+03 -1.880370e+03 -1.729370e+03 -1.798370e+03
  -1.908370e+03 -1.904370e+03 -1.874370e+03]]
MDRPK026
[[-3.26479e+05 -1.09292e+05 -9.19100e+03  5.00000e+00 -2.73000e+02
  -2.61000e+02 -2.03420e+04 -3.66890e+04 -1.46910e+04 -3.91000e+02
  -1.66910e+04 -7.39100e+03]
 [-3.26201e+05 -1.09015e+05 -8.91300e+03 -2.75000e+02  3.00000e+00
  -5.41000e+02 -2.00660e+04 -3.64130e+04 -1.44130e+04 -1.11000e+02
  -1.64130e+04 -7.11300e+03]
 [-3.17285e+05 -1.00099e+05  3.00000e+00 -9.19100e+03 -8.91300e+03
  -9.45700e+03 -1.11500e+04 -2.74970e+04 -5.49700e+03 -8.79700e+03
  -7.49600e+03 -1.79700e+03]
 [-3.11784e+05 -9.45990e+04 -5.49600e+03 -1.46910e+04 -1.44130e+04
  -1.49570e+04 -5.65000e+03 -2.19970e+04  5.00000e+00 -1.42970e+04
  -1.99700e+03 -7.29600e+03]
 [-2.89185e+05 -7.19990e+04 -2.80970e+04 -3.72910e+04 -3.70130e+04
  -3.75570e+04 -1.69440e+04 -5.97000e+02 -2.25970e+04 -3.68970e+04
  -2.05970e+04 -2.98970e+04]]
MDRS2001
[[-5.00000000e+01 -1.95000000e+02 -1.59500000e+03 -9.30000000e+01
   2.00000000e+00 -8.52928932e+01 -9.99999995e+08]
 [-1.54229289e+03 -1.39729289e+03  2.70710678e+00 -1.49929289e+03
  -1.59629289e+03 -1.50750000e+03 -9.99998397e+08]
 [-4.00000000e+01 -9.90000000e+01 -1.49900000e+03  3.00000000e+00
  -9.40000000e+01 -5.29289322e+00 -9.99999899e+08]
 [-4.20000000e+01 -1.00000000e+02 -1.50100000e+03  1.00000000e+00
  -9.60000000e+01 -7.29289322e+00 -9.99999901e+08]
 [-4.93000000e+01 -1.95300000e+02 -1.59530000e+03 -9.33000000e+01
   2.30000000e+00 -8.55928932e+01 -9.99999994e+08]]
MDRSD034
[[ 4.00000000e+00 -2.35252000e+05 -4.60660000e+05 -9.53925400e+06
  -9.53925400e+06 -2.43392540e+07 -4.59740000e+05 -4.60710000e+05
  -4.60675000e+05 -4.59493000e+05 -4.21658000e+05 -4.48744000e+05
  -4.60471000e+05 -4.26521000e+05 -4.49978000e+05 -2.82280000e+05

ValueError: zero-size array to reduction operation maximum which has no identity

In [65]:
match_idxs

[array([ 0,  0,  9,  0,  3,  7,  8,  4, 10,  0,  2,  6,  0,  0,  0,  2,  6,
         3,  7,  8,  0,  2,  6]),
 array([0, 0, 0, 5, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 16,  0,  1,  2,  4,  5,  6,
         7,  8,  9, 10, 16, 17,  0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 16,
        17, 11, 12, 13,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
        13, 14, 15, 16, 17,  0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 16, 17,
         0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 16, 17,  0,  1,  2,  4,  5,
         6,  7,  8,  9, 10, 16, 17,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
        10, 11, 12, 13, 14, 15, 16, 17,  0,  1,  2,  4,  5,  6,  7,  8,  9,
        10, 16, 17]),
 array([ 0,  8,  1,  9,  2, 11,  4,  5, 12, 13, 15,  4,  5, 12, 13, 15,  6,
         7,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         0,  8,  1,  9, 10,  2, 11,  4,  5, 12, 13, 15,  4,  5, 12, 13, 15,
         0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([4, 5, 0, 4, 6, 1, 2, 0, 1, 2, 3, 4, 5, 6, 7]),
 array([ 0,  9,  1, 10, 23, 11, 21,  0,  9,  1,  0,  9,  4,  5,  7,  8, 38,
        39, 40, 41, 42, 43, 44, 45, 38, 39, 40, 41, 42, 43, 44, 45]),
 array([0, 1, 2, 0, 1]),
 array([ 8,  0,  2,  4,  7,  8, 16, 17, 22,  0,  4,  7,  3,  9, 11, 15, 18,
        19, 20, 23,  2, 16, 17,  0,  4,  0,  2,  4,  8, 16, 17, 22,  8,  3,
         9, 11, 15, 18, 19, 20,  5, 13, 14, 21]),
 array([ 0,  2,  4,  5, 11, 18, 29,  0,  3,  4,  5, 12, 18, 29,  5,  0,  4,
         5, 18, 29,  6, 22, 23, 24, 25, 26, 28,  0,  4,  5, 15, 18, 29, 27,
         0,  4,  5,  6,  7,  8,  9, 10, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30]),
 array([ 2,  2,  2,  3,  4,  5,  6,  7,  8, 15,  4,  2,  3,  4,  5,  6,  7,
         6,  7,  1,  2,  3,  4,  5,  6,  7,  2,  3,  4,  5,  6,  7,  2,  3,
         4,  5,  6,  7, 14,  2,  3,  4,  5,  6,  7, 10, 11, 12, 13, 19]),
 array([ 1, 12, 12, 15, 12, 16, 17, 27, 28, 29, 30, 31, 32, 16, 17, 27, 28,
        29, 30, 31, 32, 19, 20,  3, 61,  4, 10, 53, 61]),
 array([0, 0, 0]),
 array([ 0,  1,  6,  7,  9, 20, 34, 55, 64, 69, 71, 74,  0,  1,  6,  7,  9,
        20, 34, 55, 64, 69, 71, 74]),
 array([ 3,  4,  0,  5,  6,  7,  8,  9, 10,  0,  5,  6,  7,  8,  9, 10,  0,
         5,  6,  7,  8,  9, 10,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
         0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 27,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10]),
 array([0, 6, 5, 5, 5, 2, 5, 3, 5, 4, 5, 2])]

## Match

In [ ]:
#compute cosine distance
matching_cols = matching_cols + ["impactValue"]

dist_mat = np.full((len(ext_vect_df), len(lab_vect_df), len(matching_cols)), np.nan)
for k, col in enumerate(matching_cols):
    if col == "impactValue":
        # add negative absolute diff for impact value
        # dist must be negative as we want to maximize similarity
        dist_mat[:,:,k] = -np.abs(extracted_df["impactValue"].values.reshape(-1, 1) - labelled_df["impactValue"].values.reshape(1, -1))
    else: #compute cosine similarity
        # Convert Series of arrays/lists to 2D numpy arrays
        X = np.stack(ext_vect_df[col].values) #nsamples, nfeatures
        Y = np.stack(lab_vect_df[col].values)
        # Compute cosine similarity
        dist_mat[:,:,k] = cosine_similarity(X, Y)

In [ ]:
#find match idx from cosine matrix
match_idx = dist_mat.sum(axis=2).argmax(axis=1)

#join extracted and labelled dataframes
repeated_df = labelled_df.loc[np.repeat(match_idx, 1)].reset_index(drop=True)
repeated_df = repeated_df.add_suffix('_matched')
joined_df = pd.concat([extracted_df, repeated_df], axis=1)

In [ ]:
joined_df.sort_index(axis=1)

,appealCode,appealCode_matched,comments_matched,country,country_iso3,country_iso3_kw,country_iso3_kw_matched,country_iso3_matched,country_kw,country_matched,...,reportDate_matched,reportLink,startDay,startDay_matched,startMonth,startMonth_matched,startYear,startYear_matched,unit_type,unit_type_matched
0,MDR55001,MDRBD022,NaN,"[Kiribati, Papua New Guinea, Solomon Islands, ...",NaN,FJI,NaN,NaN,Fiji,[Bangladesh],...,2019-07-19,https://adore.ifrc.org/Download.aspx?FileId=16...,NaN,16.0,NaN,7.0,NaN,2019.0,other,other
1,MDR55001,MDRBD022,NaN,"[Kiribati, Papua New Guinea, Solomon Islands, ...",NaN,FJI,NaN,NaN,Fiji,[Bangladesh],...,2019-07-19,https://adore.ifrc.org/Download.aspx?FileId=16...,NaN,16.0,NaN,7.0,NaN,2019.0,other,other
2,MDR55001,MDRBD022,NaN,[Vanuatu],NaN,FJI,NaN,NaN,Fiji,[Bangladesh],...,2019-07-19,https://adore.ifrc.org/Download.aspx?FileId=16...,NaN,16.0,NaN,7.0,NaN,2019.0,other,other
3,MDR55001,MDRBD022,NaN,[Vanuatu],NaN,FJI,NaN,NaN,Fiji,[Bangladesh],...,2019-07-19,https://adore.ifrc.org/Download.aspx?FileId=16...,NaN,16.0,NaN,7.0,NaN,2019.0,other,other
4,MDR55001,MDRBD022,NaN,[Tuvalu],NaN,FJI,NaN,NaN,Fiji,[Bangladesh],...,2019-07-19,https://adore.ifrc.org/Download.aspx?FileId=16...,NaN,16.0,NaN,7.0,NaN,2019.0,other,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,MDRZM022,MDRBD022,NaN,[Zambia],NaN,ZMB,NaN,NaN,Zambia,[Bangladesh],...,2019-07-19,https://adore.ifrc.org/Download.aspx?FileId=84...,NaN,18.0,NaN,7.0,2023.0,2019.0,other,other
271,MDRZM022,MDRBD022,NaN,[Zambia],NaN,ZMB,NaN,NaN,Zambia,[Bangladesh],...,2019-07-19,https://adore.ifrc.org/Download.aspx?FileId=84...,NaN,18.0,NaN,7.0,2023.0,2019.0,other,other
272,MDRZM022,MDRBD022,NaN,[Zambia],NaN,ZMB,NaN,NaN,Zambia,[Bangladesh],...,2019-07-19,https://adore.ifrc.org/Download.aspx?FileId=84...,NaN,16.0,NaN,7.0,2024.0,2019.0,other,other
273,MDRZM022,MDRBD022,NaN,[Zambia],NaN,ZMB,NaN,NaN,Zambia,[Bangladesh],...,2019-07-19,https://adore.ifrc.org/Download.aspx?FileId=84...,NaN,18.0,NaN,7.0,NaN,2019.0,other,other
274,MDRZM022,MDRBD022,NaN,[Zambia],NaN,ZMB,NaN,NaN,Zambia,[Bangladesh],...,2019-07-19,https://adore.ifrc.org/Download.aspx?FileId=84...,NaN,18.0,NaN,7.0,NaN,2019.0,other,other

In [ ]:
repeated_df

,matched_reportDate,matched_impactSubtype,matched_impactValue,matched_impactUnit,matched_impactValuePrecision,matched_impactValueMin,matched_impactValueMax,matched_impactsAnnotation,matched_country,matched_location,...,matched_endDay,matched_hazards,matched_appealCode,matched_comments,matched_country_iso3,matched_country_iso3_kw,matched_hazards_reclass,matched_impactValueOrig,matched_impactUnitOrig,matched_unit_type
0,2019-07-19,Other Infrastructure Impacts,NaN,unknown,NaN,NaN,NaN,[It is also reported that embankments have bee...,[Bangladesh],"[Kurigram district, Gaibandha district, Lalmon...",...,NaN,[Flood],MDRBD022,NaN,NaN,NaN,['Flood'],NaN,NaN,other
1,2019-07-19,Other Infrastructure Impacts,NaN,unknown,NaN,NaN,NaN,[It is also reported that embankments have bee...,[Bangladesh],"[Kurigram district, Gaibandha district, Lalmon...",...,NaN,[Flood],MDRBD022,NaN,NaN,NaN,['Flood'],NaN,NaN,other
2,2019-07-19,Other Infrastructure Impacts,NaN,unknown,NaN,NaN,NaN,[It is also reported that embankments have bee...,[Bangladesh],"[Kurigram district, Gaibandha district, Lalmon...",...,NaN,[Flood],MDRBD022,NaN,NaN,NaN,['Flood'],NaN,NaN,other
3,2019-07-19,Other Infrastructure Impacts,NaN,unknown,NaN,NaN,NaN,[It is also reported that embankments have bee...,[Bangladesh],"[Kurigram district, Gaibandha district, Lalmon...",...,NaN,[Flood],MDRBD022,NaN,NaN,NaN,['Flood'],NaN,NaN,other
4,2019-07-19,Other Infrastructure Impacts,NaN,unknown,NaN,NaN,NaN,[It is also reported that embankments have bee...,[Bangladesh],"[Kurigram district, Gaibandha district, Lalmon...",...,NaN,[Flood],MDRBD022,NaN,NaN,NaN,['Flood'],NaN,NaN,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2019-07-19,Affected People,2176519.0,people,exact,NaN,NaN,[DREF operation n MDRBD022 Glide n FL-2019-000...,[Bangladesh],[],...,18.0,[Flood],MDRBD022,NaN,NaN,NaN,['Flood'],2176519.0,people,other
271,2019-07-19,Affected People,2176519.0,people,exact,NaN,NaN,[DREF operation n MDRBD022 Glide n FL-2019-000...,[Bangladesh],[],...,18.0,[Flood],MDRBD022,NaN,NaN,NaN,['Flood'],2176519.0,people,other
272,2019-07-19,Other Infrastructure Impacts,NaN,unknown,NaN,NaN,NaN,[It is also reported that embankments have bee...,[Bangladesh],"[Kurigram district, Gaibandha district, Lalmon...",...,NaN,[Flood],MDRBD022,NaN,NaN,NaN,['Flood'],NaN,NaN,other
273,2019-07-19,Affected People,2176519.0,people,exact,NaN,NaN,[DREF operation n MDRBD022 Glide n FL-2019-000...,[Bangladesh],[],...,18.0,[Flood],MDRBD022,NaN,NaN,NaN,['Flood'],2176519.0,people,other
274,2019-07-19,Affected People,2176519.0,people,exact,NaN,NaN,[DREF operation n MDRBD022 Glide n FL-2019-000...,[Bangladesh],[],...,18.0,[Flood],MDRBD022,NaN,NaN,NaN,['Flood'],2176519.0,people,other

In [ ]:
extracted_df

,impactSubtype,impactValue,impactUnit,impactValuePrecision,country,location,startYear,startMonth,startDay,endYear,...,reportLink,disasterType,nathaz_text,impactType,country_iso3,country_iso3_kw,hazards_reclass,impactValueOrig,impactUnitOrig,unit_type
0,Affected People,43880.0,people,exact,"[Kiribati, Papua New Guinea, Solomon Islands, ...",[],NaN,NaN,NaN,NaN,...,https://adore.ifrc.org/Download.aspx?FileId=16...,Cyclone,['He explained clearly what the indicators mea...,NaN,NaN,FJI,['Tropical storm'],43880.0,people,other
1,Affected People,34573.0,people,exact,"[Kiribati, Papua New Guinea, Solomon Islands, ...",[],NaN,NaN,NaN,NaN,...,https://adore.ifrc.org/Download.aspx?FileId=16...,Cyclone,['He explained clearly what the indicators mea...,NaN,NaN,FJI,['Tropical storm'],34573.0,people,other
2,Residential Buildings,900.0,homes,exact,[Vanuatu],[West Tanna],NaN,NaN,NaN,NaN,...,https://adore.ifrc.org/Download.aspx?FileId=16...,Cyclone,['He explained clearly what the indicators mea...,NaN,NaN,FJI,['Tropical storm'],900.0,houses,other
3,Human Health and Wellbeing,85.0,unknown,exact,[Vanuatu],[],NaN,NaN,NaN,NaN,...,https://adore.ifrc.org/Download.aspx?FileId=16...,Cyclone,['He explained clearly what the indicators mea...,NaN,NaN,FJI,['Tropical storm'],85.0,per cent,other
4,"Access to Water, Sanitation, and Hygiene",414.0,people,exact,[Tuvalu],[],NaN,NaN,NaN,NaN,...,https://adore.ifrc.org/Download.aspx?FileId=16...,Cyclone,['He explained clearly what the indicators mea...,NaN,NaN,FJI,['Tropical storm'],138.0,households,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,Crop Production and Forestry,NaN,undefined crop production and forestry,NaN,[Zambia],[],2023.0,NaN,NaN,2024.0,...,https://adore.ifrc.org/Download.aspx?FileId=84...,Drought,['SITUATION ANALYSIS Description of the crisis...,NaN,NaN,ZMB,['Drought'],NaN,NaN,other
271,Affected Livestock and Animals,NaN,undefined affected animals,NaN,[Zambia],[],2023.0,NaN,NaN,2024.0,...,https://adore.ifrc.org/Download.aspx?FileId=84...,Drought,['SITUATION ANALYSIS Description of the crisis...,NaN,NaN,ZMB,['Drought'],NaN,NaN,other
272,Other Economic and Livelihood Impacts,11.0,CHF,exact,[Zambia],[],2024.0,NaN,NaN,NaN,...,https://adore.ifrc.org/Download.aspx?FileId=84...,Drought,['SITUATION ANALYSIS Description of the crisis...,NaN,NaN,ZMB,['Drought'],11.0,CHF million,other
273,Access to Food,NaN,people,NaN,[Zambia],[],NaN,NaN,NaN,NaN,...,https://adore.ifrc.org/Download.aspx?FileId=84...,Drought,['SITUATION ANALYSIS Description of the crisis...,NaN,NaN,ZMB,['Drought'],NaN,NaN,other
274,Water Quality and Availability,NaN,unknown,NaN,[Zambia],[],NaN,NaN,NaN,NaN,...,https://adore.ifrc.org/Download.aspx?FileId=84...,Drought,['SITUATION ANALYSIS Description of the crisis...,NaN,NaN,ZMB,['Drought'],NaN,NaN,other