In [120]:
import pandas as pd
import datetime as dt
import os
import pathlib
from src.data import *
from src.labelling_helpers import *

In [121]:
# load all reports containing mdr in filename
report_dir = pathlib.Path(DATA_LABELLED / "v24062026")
mdr_paths = list(report_dir.rglob("*MDR*.csv"))

In [122]:
mdr_reports = pd.concat([pd.read_csv(path) for path in mdr_paths], ignore_index=True)

In [123]:
mdr_reports.appealCode.nunique()

12

In [124]:
mdr_reports

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,annotation,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,appealCode
0,2025-12-08,Affected People,1024200.0,people,exact,NaN,NaN,['Appeal: Total DREF Allocation Crisis Categor...,['Lebanon'],"['Bekaa', 'North']",2023.0,2.0,21.0,2023.0,5.0,30.0,['Cold wave'],MDRLB013
1,2025-12-08,Targeted People,11890.0,people,exact,NaN,NaN,['Appeal: Total DREF Allocation Crisis Categor...,['Lebanon'],"['Bekaa', 'North']",2023.0,2.0,21.0,2023.0,5.0,30.0,['Cold wave'],MDRLB013
2,2025-12-08,Access to Education,NaN,NaN,NaN,NaN,NaN,"['On 6 February, the weather deteriorated in t...",['Lebanon'],"['Bekaa', 'North']",2023.0,2.0,6.0,2023.0,2.0,9.0,['Cold wave'],MDRLB013
3,2025-12-08,NaN,NaN,NaN,NaN,NaN,NaN,[],['Lebanon'],"['Bekaa', 'North']",2023.0,2.0,21.0,2023.0,5.0,30.0,['Cold wave'],MDRLB013
4,2025-12-08,Affected People,NaN,NaN,NaN,NaN,NaN,['Data from Interagency Coordination Lebanon i...,['Lebanon'],"['Bekaa', 'Beirut', 'Mount Lebanon', 'South', ...",2023.0,2.0,21.0,2023.0,5.0,30.0,['Cold wave'],MDRLB013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,2018-11-24,Human Deaths,100.0,people,approx,NaN,NaN,"['Approximately over 100 people dead, with mos...",['Papua New Guinea'],"['Western Highland', 'Southern Highlands', 'He...",2018.0,2.0,26.0,2018.0,7.0,27.0,"['Earthquake', 'Mass movement']",MDRPG008
227,2018-11-24,Affected people,NaN,people,approx,270000.0,NaN,"['Earthquake affected over 270,000 people, who...",['Papua New Guinea'],"['Western Highland', 'Southern Highlands', 'He...",2018.0,2.0,26.0,2018.0,7.0,27.0,['Earthquake'],MDRPG008
228,2018-11-24,Road Infrastructure,NaN,NaN,NaN,NaN,NaN,"['Planning commenced in earnest, once the DREF...",['Papua New Guinea'],"['Western Highland', 'Southern Highlands', 'He...",2018.0,2.0,26.0,NaN,NaN,NaN,['Earthquake'],MDRPG008
229,2018-11-24,Mobility and Access to Transport,NaN,NaN,NaN,NaN,NaN,"['Planning commenced in earnest, once the DREF...",['Papua New Guinea'],"['Western Highland', 'Southern Highlands', 'He...",2018.0,2.0,26.0,NaN,NaN,NaN,['Earthquake'],MDRPG008
230,2018-11-24,IT and Communication Infrastructure,NaN,NaN,NaN,NaN,NaN,['The most remote locations could only be acce...,['Papua New Guinea'],"['Western Highland', 'Southern Highlands', 'He...",2018.0,2.0,26.0,NaN,NaN,NaN,['Earthquake'],MDRPG008

In [125]:
# other reports
label_v1 = pd.read_csv(DATA_LABELLED / "labelled_reports_impacts_gaps_v050426.csv")
cecily = pd.read_csv(report_dir / "red_crosslabelled_reports_cecily.csv")

In [126]:
label_v1

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,annotation,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,appealCode,comments
0,2019-03-14,Affected People,1381000.0,people,exact,NaN,NaN,['SITUATION ANALYSIS Description of the disast...,['China'],"['Deyang', 'Mianyang', 'Guangyuan']",2018.0,7.0,7.0,2018.0,7.0,13.0,"['Flood', 'Tropical storm']",MDRCN006,NaN
1,2019-03-14,Human Deaths,3.0,people,exact,NaN,NaN,['SITUATION ANALYSIS Description of the disast...,['China'],"['Deyang', 'Mianyang', 'Guangyuan']",2018.0,7.0,7.0,2018.0,7.0,13.0,"['Flood', 'Tropical storm']",MDRCN006,NaN
2,2019-03-14,Displaced People,222000.0,people,exact,NaN,NaN,['SITUATION ANALYSIS Description of the disast...,['China'],"['Deyang', 'Mianyang', 'Guangyuan']",2018.0,7.0,7.0,2018.0,7.0,13.0,"['Flood', 'Tropical storm']",MDRCN006,NaN
3,2019-03-14,Residential Buildings,NaN,houses collapsed,approx,900.0,NaN,['SITUATION ANALYSIS Description of the disast...,['China'],"['Deyang', 'Mianyang', 'Guangyuan']",2018.0,7.0,7.0,2018.0,7.0,13.0,"['Flood', 'Tropical storm']",MDRCN006,NaN
4,2019-03-14,Residential Buildings,NaN,houses damaged,approx,29000.0,NaN,['SITUATION ANALYSIS Description of the disast...,['China'],"['Deyang', 'Mianyang', 'Guangyuan']",2018.0,7.0,7.0,2018.0,7.0,13.0,"['Flood', 'Tropical storm']",MDRCN006,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,2024-10-02,Crop Production and Forestry,NaN,NaN,approx,NaN,NaN,['1 OPERATION UPDATE Mozambique | Drought Emer...,['Mozambique'],[],2024.0,3.0,NaN,NaN,NaN,NaN,['Tropical storm'],MDRMZ024,NaN
503,2024-10-02,Other Service Access Impacts,NaN,NaN,approx,NaN,NaN,['1 OPERATION UPDATE Mozambique | Drought Emer...,['Mozambique'],[],2024.0,3.0,NaN,NaN,NaN,NaN,"['Drought', 'Tropical storm']",MDRMZ024,NaN
504,2024-10-02,Crop Production and Forestry,690000.0,hectares of crops,exact,NaN,NaN,['1 OPERATION UPDATE Mozambique | Drought Emer...,['Mozambique'],"['Tete', 'Gaza', 'Manica', 'Inhambane']",2024.0,3.0,NaN,2024.0,4.0,NaN,"['Drought', 'Tropical storm']",MDRMZ024,NaN
505,2024-10-02,Access to Food,2700000.0,people,NaN,NaN,NaN,['1 OPERATION UPDATE Mozambique | Drought Emer...,['Mozambique'],[],2024.0,NaN,NaN,2024.0,7.0,NaN,"['Drought', 'Tropical storm']",MDRMZ024,NaN
506,2024-10-02,Other Economic and Livelihood Impacts,3.0,\% inflation rate,NaN,NaN,NaN,['1 OPERATION UPDATE Mozambique | Drought Emer...,['Mozambique'],[],2024.0,NaN,NaN,2024.0,6.0,NaN,"['Drought', 'Tropical storm']",MDRMZ024,NaN

In [127]:
label_v1.appealCode.nunique()

18

In [128]:
cecily

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,annotation,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,appealCode,comments
0,2025-12-08,Affected People,2000.0,people,exact,NaN,NaN,['DREF Final Report Jordan Cold Wave 2023 Appe...,['Jordan'],"['Ajloun', 'Karak', 'Mafraq', 'Amman', 'Taleh'...",2023,11,19,2024.0,3.0,31.0,"['Extreme cold temperature', 'Other storm']",MDRJO003,NaN
1,2025-12-08,Targeted People,2000.0,people,exact,NaN,NaN,['DREF Final Report Jordan Cold Wave 2023 Appe...,['Jordan'],"['Ajloun', 'Karak', 'Mafraq', 'Amman', 'Taleh'...",2023,11,19,2024.0,3.0,31.0,"['Extreme cold temperature', 'Other storm']",MDRJO003,NaN
2,2025-12-08,Assisted People,2000.0,people,exact,NaN,NaN,['DREF Final Report Jordan Cold Wave 2023 Appe...,['Jordan'],"['Ajloun', 'Karak', 'Mafraq', 'Amman', 'Taleh'...",2023,11,19,2024.0,3.0,31.0,"['Extreme cold temperature', 'Other storm']",MDRJO003,NaN
3,2025-12-08,DREF Allocation & Funding requirements,291629.0,CHF,exact,NaN,NaN,['DREF Final Report Jordan Cold Wave 2023 Appe...,['Jordan'],"['Ajloun', 'Karak', 'Mafraq', 'Amman', 'Taleh'...",2023,11,19,2024.0,3.0,31.0,"['Extreme cold temperature', 'Other storm']",MDRJO003,NaN
4,2025-12-08,Residential Buildings,NaN,NaN,NaN,NaN,NaN,['Floodwaters entered homes in affected govern...,['Jordan'],"['Ajloun', 'Karak', 'Mafraq', 'Amman', 'Taleh'...",2023,11,19,NaN,NaN,NaN,['Other storm'],MDRJO003,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,2025-12-08,"Water, Sanitation, and Hygiene Infrastructure",NaN,NaN,NaN,NaN,NaN,['The first needs identified per sector are Sh...,['Cameroon'],['Mbankolo neighborhood'],2023,10,8,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN
63,2025-12-08,Water Quality and Availability,NaN,NaN,NaN,NaN,NaN,['The first needs identified per sector are Sh...,['Cameroon'],['Mbankolo neighborhood'],2023,10,8,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN
64,2025-12-08,Human Health and Wellbeing,NaN,NaN,NaN,NaN,NaN,['The first needs identified per sector are Sh...,['Cameroon'],['Mbankolo neighborhood'],2023,10,8,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN
65,2025-12-08,Infected and Ill People,NaN,NaN,NaN,NaN,NaN,['The first needs identified per sector are Sh...,['Cameroon'],['Mbankolo neighborhood'],2023,10,8,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN
66,2025-12-08,Economy and Livelihood,NaN,NaN,NaN,NaN,NaN,"['These people have lost almost everything, as...",['Cameroon'],['Mbankolo neighborhood'],2023,10,8,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN

In [129]:
cecily.appealCode.nunique()

4

In [130]:
# concatenate all labelled reports
labelled_reports_all = pd.concat([mdr_reports, label_v1, cecily], axis=0, ignore_index=True)

In [131]:
labelled_reports_all

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,annotation,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,appealCode,comments
0,2025-12-08,Affected People,1024200.0,people,exact,NaN,NaN,['Appeal: Total DREF Allocation Crisis Categor...,['Lebanon'],"['Bekaa', 'North']",2023.0,2.0,21.0,2023.0,5.0,30.0,['Cold wave'],MDRLB013,NaN
1,2025-12-08,Targeted People,11890.0,people,exact,NaN,NaN,['Appeal: Total DREF Allocation Crisis Categor...,['Lebanon'],"['Bekaa', 'North']",2023.0,2.0,21.0,2023.0,5.0,30.0,['Cold wave'],MDRLB013,NaN
2,2025-12-08,Access to Education,NaN,NaN,NaN,NaN,NaN,"['On 6 February, the weather deteriorated in t...",['Lebanon'],"['Bekaa', 'North']",2023.0,2.0,6.0,2023.0,2.0,9.0,['Cold wave'],MDRLB013,NaN
3,2025-12-08,NaN,NaN,NaN,NaN,NaN,NaN,[],['Lebanon'],"['Bekaa', 'North']",2023.0,2.0,21.0,2023.0,5.0,30.0,['Cold wave'],MDRLB013,NaN
4,2025-12-08,Affected People,NaN,NaN,NaN,NaN,NaN,['Data from Interagency Coordination Lebanon i...,['Lebanon'],"['Bekaa', 'Beirut', 'Mount Lebanon', 'South', ...",2023.0,2.0,21.0,2023.0,5.0,30.0,['Cold wave'],MDRLB013,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800,2025-12-08,"Water, Sanitation, and Hygiene Infrastructure",NaN,NaN,NaN,NaN,NaN,['The first needs identified per sector are Sh...,['Cameroon'],['Mbankolo neighborhood'],2023.0,10.0,8.0,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN
801,2025-12-08,Water Quality and Availability,NaN,NaN,NaN,NaN,NaN,['The first needs identified per sector are Sh...,['Cameroon'],['Mbankolo neighborhood'],2023.0,10.0,8.0,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN
802,2025-12-08,Human Health and Wellbeing,NaN,NaN,NaN,NaN,NaN,['The first needs identified per sector are Sh...,['Cameroon'],['Mbankolo neighborhood'],2023.0,10.0,8.0,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN
803,2025-12-08,Infected and Ill People,NaN,NaN,NaN,NaN,NaN,['The first needs identified per sector are Sh...,['Cameroon'],['Mbankolo neighborhood'],2023.0,10.0,8.0,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN
804,2025-12-08,Economy and Livelihood,NaN,NaN,NaN,NaN,NaN,"['These people have lost almost everything, as...",['Cameroon'],['Mbankolo neighborhood'],2023.0,10.0,8.0,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN

In [132]:
labelled_reports_all.appealCode.nunique()

34

In [133]:
# check missing appeals
appeal_codes = [
    "MDRDZ011",
    "MDRPK026",
    "MDRCM039",
    "MDRBJ019",
    "MDRSD034",
    "MDRNG041",
    "MDRRW022",
    "MDRZM022",
    "MDRUG050",
    "MDRMZ024",
    "MDRIR009",
    "MDRTP004",
    "MDRVU012",
    "MDRDZ007",
    "MDRAF014",
    "MDRCM036",
    "MDRDZ008",
    "MDRPH036",
    "MDRHT018",
    "MDRID013",
    "MDR55001",
    "MDRJO003",
    "MDRLB013",
    "MDRPK018",
    "MDRTJ035",
    "MDRCN006",
    "MDRBD022",
    "MDRYE011",
    "MDRS2001",
    "MDRIQ014",
    "MDRGN015",
    "MDRSV012",
    "MDRMY003",
    "MDRBD015",
    "MDRKE058",
    "MDRCO023",
    "MDRGW003",
    "MDRHU005",
    "MDRPH021",
    "MDRRS015",
    "MDRMN017",
    "MDRGT009",
    "MDRPG008",
    "MDREC019",
    "MDRTN010",
    "MDRCR012",
    "MDRGE019",
    "MDRKZ010",
    "MDRUY004",
]
appeals_missing = [
    code
    for code in appeal_codes
    if code not in labelled_reports_all.appealCode.unique()
]

In [134]:
appeals_missing

['MDRTP004',
 'MDRDZ007',
 'MDRAF014',
 'MDRHT018',
 'MDR55001',
 'MDRGN015',
 'MDRBD015',
 'MDRCO023',
 'MDRGW003',
 'MDRHU005',
 'MDRPH021',
 'MDRGT009',
 'MDRTN010',
 'MDRCR012',
 'MDRGE019']

In [135]:
def reformat_date(x):
    if "/" in x:
        day, month, year = x.split("/")
        return f"{year}-{month}-{day}"
    else:
        return x
labelled_reports_all["reportDate_orig"] = labelled_reports_all.reportDate
labelled_reports_all.reportDate = labelled_reports_all.reportDate.apply(reformat_date)
labelled_reports_all.reportDate = pd.to_datetime(labelled_reports_all.reportDate, errors="coerce")

In [136]:
labelled_reports_all

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,annotation,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,appealCode,comments,reportDate_orig
0,2025-12-08,Affected People,1024200.0,people,exact,NaN,NaN,['Appeal: Total DREF Allocation Crisis Categor...,['Lebanon'],"['Bekaa', 'North']",2023.0,2.0,21.0,2023.0,5.0,30.0,['Cold wave'],MDRLB013,NaN,2025-12-08
1,2025-12-08,Targeted People,11890.0,people,exact,NaN,NaN,['Appeal: Total DREF Allocation Crisis Categor...,['Lebanon'],"['Bekaa', 'North']",2023.0,2.0,21.0,2023.0,5.0,30.0,['Cold wave'],MDRLB013,NaN,2025-12-08
2,2025-12-08,Access to Education,NaN,NaN,NaN,NaN,NaN,"['On 6 February, the weather deteriorated in t...",['Lebanon'],"['Bekaa', 'North']",2023.0,2.0,6.0,2023.0,2.0,9.0,['Cold wave'],MDRLB013,NaN,2025-12-08
3,2025-12-08,NaN,NaN,NaN,NaN,NaN,NaN,[],['Lebanon'],"['Bekaa', 'North']",2023.0,2.0,21.0,2023.0,5.0,30.0,['Cold wave'],MDRLB013,NaN,2025-12-08
4,2025-12-08,Affected People,NaN,NaN,NaN,NaN,NaN,['Data from Interagency Coordination Lebanon i...,['Lebanon'],"['Bekaa', 'Beirut', 'Mount Lebanon', 'South', ...",2023.0,2.0,21.0,2023.0,5.0,30.0,['Cold wave'],MDRLB013,NaN,2025-12-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800,2025-12-08,"Water, Sanitation, and Hygiene Infrastructure",NaN,NaN,NaN,NaN,NaN,['The first needs identified per sector are Sh...,['Cameroon'],['Mbankolo neighborhood'],2023.0,10.0,8.0,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN,2025-12-08
801,2025-12-08,Water Quality and Availability,NaN,NaN,NaN,NaN,NaN,['The first needs identified per sector are Sh...,['Cameroon'],['Mbankolo neighborhood'],2023.0,10.0,8.0,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN,2025-12-08
802,2025-12-08,Human Health and Wellbeing,NaN,NaN,NaN,NaN,NaN,['The first needs identified per sector are Sh...,['Cameroon'],['Mbankolo neighborhood'],2023.0,10.0,8.0,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN,2025-12-08
803,2025-12-08,Infected and Ill People,NaN,NaN,NaN,NaN,NaN,['The first needs identified per sector are Sh...,['Cameroon'],['Mbankolo neighborhood'],2023.0,10.0,8.0,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN,2025-12-08
804,2025-12-08,Economy and Livelihood,NaN,NaN,NaN,NaN,NaN,"['These people have lost almost everything, as...",['Cameroon'],['Mbankolo neighborhood'],2023.0,10.0,8.0,NaN,NaN,NaN,['Mass movement'],MDRCM036,NaN,2025-12-08

In [137]:
labelled_reports_all[["reportDate_orig", "reportDate"]].groupby("reportDate").head(1)

    reportDate_orig reportDate
0        2025-12-08 2025-12-08
17       12/10/2025 2025-10-12
59        12/8/2025 2025-08-12
71       2022-04-01 2022-04-01
111      2021-09-20 2021-09-20
143      2022-04-12 2022-04-12
166      2020-11-30 2020-11-30
223      2018-11-24 2018-11-24
231      2019-03-14 2019-03-14
246      2019-07-19 2019-07-19
258      2022-08-03 2022-08-03
295      2024-08-06 2024-08-06
322      2021-12-27 2021-12-27
332      2019-06-26 2019-06-26
343      2017-11-21 2017-11-21
346      2024-04-26 2024-04-26
381      2024-09-06 2024-09-06
410      2024-04-02 2024-04-02
420      2024-08-30 2024-08-30
518      2024-09-22 2024-09-22
541      2025-03-28 2025-03-28
572      2024-09-13 2024-09-13
591      2024-09-07 2024-09-07
614      2025-03-17 2025-03-17
702      2024-09-05 2024-09-05
730      2024-10-02 2024-10-02
756      2020-05-31 2020-05-31

In [138]:
labelled_reports_all.to_csv(DATA_LABELLED / f"labelled_reports_all_v{dt.datetime.now().strftime('%d%m%Y')}.csv", index=False)

In [139]:
reload_df = pd.read_csv(DATA_LABELLED / f"labelled_reports_all_v{dt.datetime.now().strftime('%d%m%Y')}.csv")