In [1]:
import pandas as pd
import datetime as dt
from src.data import *
from src.labelling_helpers import *

In [ ]:
# select appealCode to process
fnla = "labelled_reports_impacts_laura_nogaps_v210326.csv"
labelled_laura = pd.read_csv(DATA_LABELLED / fnla)
#labelled_laura.loc[labelled_laura["impactSubtype"].isnull(),"impactSubtype"] = labelled_laura["impactSubType"]
#labelled_laura = labelled_laura.drop(["impactSubType"],axis=1)
#labelled_laura.rename({"impactSubType":"impactSubtype"},inplace=True, axis=1)
fnlu = "labelled_reports_impacts_luca_nogaps_v190326.csv"
labelled_luca = pd.read_csv(DATA_LABELLED / fnlu)#.drop(["Unnamed: 0"],axis=1)
labelled_luca.rename({"impactSubType":"impactSubtype"},inplace=True, axis=1)
#fnga = "labelled_reports_impact_Gabriela_08_2025_fixed_appeal.csv"
#labelled_gabi = pd.read_csv(DATA_LABELLED / fnga)#.drop(["Unnamed: 0"],axis=1)
#fnana = "labelled_reports_Ana.csv"
#labelled_ana = pd.read_csv(DATA_LABELLED / fnana)#.drop(["Unnamed: 0"],axis=1)
#labelled_ana.rename({"impactSubType":"impactSubtype"},inplace=True, axis=1)


# reformat to be consistent
labelled_laura["reportDate"] = pd.to_datetime(labelled_laura["reportDate"], dayfirst=False) #reformat date to be consistent
labelled_luca["reportDate"] = pd.to_datetime(labelled_luca["reportDate"], dayfirst=False) #reformat date to be consistent
#labelled_gabi["reportDate"] = pd.to_datetime(labelled_gabi["reportDate"], dayfirst=False) #reformat date to be consistent
#labelled_ana["reportDate"] = pd.to_datetime(labelled_ana["reportDate"], dayfirst=False) #reformat date to be consistent
labelled_reports = pd.concat([labelled_laura, labelled_luca]).reset_index(drop=True)
labelled_reports.to_csv(DATA_LABELLED / f"labelled_reports_impacts_nogaps_v{dt.datetime.now().strftime('%d%m%y')}.csv", index=False)

In [ ]:
labelled_reports

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,annotation,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,appealCode,comments
0,2019-03-14,Affected People,1381000.0,people,exact,NaN,NaN,['SITUATION ANALYSIS Description of the disast...,['China'],"['Deyang', 'Mianyang', 'Guangyuan']",2018.0,7.0,7.0,2018.0,7.0,13.0,"['Flood', 'Tropical storm']",MDRCN006,NaN
1,2019-03-14,Human Deaths,3.0,people,exact,NaN,NaN,['SITUATION ANALYSIS Description of the disast...,['China'],"['Deyang', 'Mianyang', 'Guangyuan']",2018.0,7.0,7.0,2018.0,7.0,13.0,"['Flood', 'Tropical storm']",MDRCN006,NaN
2,2019-03-14,Displaced People,222000.0,people,exact,NaN,NaN,['SITUATION ANALYSIS Description of the disast...,['China'],"['Deyang', 'Mianyang', 'Guangyuan']",2018.0,7.0,7.0,2018.0,7.0,13.0,"['Flood', 'Tropical storm']",MDRCN006,NaN
3,2019-03-14,Residential Buildings,NaN,houses collapsed,approx,900.0,NaN,['SITUATION ANALYSIS Description of the disast...,['China'],"['Deyang', 'Mianyang', 'Guangyuan']",2018.0,7.0,7.0,2018.0,7.0,13.0,"['Flood', 'Tropical storm']",MDRCN006,NaN
4,2019-03-14,Residential Buildings,NaN,houses damaged,approx,29000.0,NaN,['SITUATION ANALYSIS Description of the disast...,['China'],"['Deyang', 'Mianyang', 'Guangyuan']",2018.0,7.0,7.0,2018.0,7.0,13.0,"['Flood', 'Tropical storm']",MDRCN006,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,2024-10-02,Crop Production and Forestry,NaN,NaN,approx,NaN,NaN,['1 OPERATION UPDATE Mozambique | Drought Emer...,['Mozambique'],[],2024.0,3.0,NaN,NaN,NaN,NaN,['Tropical storm'],MDRMZ024,NaN
441,2024-10-02,Other Service Access Impacts,NaN,NaN,approx,NaN,NaN,['1 OPERATION UPDATE Mozambique | Drought Emer...,['Mozambique'],[],2024.0,3.0,NaN,NaN,NaN,NaN,"['Drought', 'Tropical storm']",MDRMZ024,NaN
442,2024-10-02,Crop Production and Forestry,690000.0,hectares of crops,exact,NaN,NaN,['1 OPERATION UPDATE Mozambique | Drought Emer...,['Mozambique'],"['Tete', 'Gaza', 'Manica', 'Inhambane']",2024.0,3.0,NaN,2024.0,4.0,NaN,"['Drought', 'Tropical storm']",MDRMZ024,NaN
443,2024-10-02,Access to Food,2700000.0,people,NaN,NaN,NaN,['1 OPERATION UPDATE Mozambique | Drought Emer...,['Mozambique'],[],2024.0,NaN,NaN,2024.0,7.0,NaN,"['Drought', 'Tropical storm']",MDRMZ024,NaN
444,2024-10-02,Other Economic and Livelihood Impacts,3.0,\% inflation rate,NaN,NaN,NaN,['1 OPERATION UPDATE Mozambique | Drought Emer...,['Mozambique'],[],2024.0,NaN,NaN,2024.0,6.0,NaN,"['Drought', 'Tropical storm']",MDRMZ024,NaN

In [3]:
# gather extracted reports
ext_df1 = pd.read_csv(
    DATA_OUT_LLMS
    / "0-350_latest_reports_1quali_chunksize1000_Noneit_meta-llama_llama-4-scout-17b-16e-instruct_v200426.csv"
)
ext_df2 = pd.read_csv(
    DATA_OUT_LLMS
    / "350-718_latest_reports_1quali_chunksize1000_Noneit_meta-llama_llama-4-scout-17b-16e-instruct_v220426.csv"
)
ext_df3 = pd.read_csv(
    DATA_OUT_LLMS
    / "482-718_latest_reports_1quali_chunksize1000_Noneit_meta-llama_llama-4-scout-17b-16e-instruct_v220426.csv"
)
# ext_df4 = pd.read_csv(DATA_OUT_LLMS / "all_appeals_longest_414-717_meta-llama_llama-4-scout-17b-16e-instruct_v111225.csv")

In [4]:
ext_df1_drop_appeal = ext_df1[ext_df1.appealCode.isin(ext_df2.appealCode)]
ext_df1_drop_appeal.appealCode.unique()

array([], dtype=object)

In [5]:
ext_df2_drop_appeal = ext_df2[ext_df2.appealCode.isin(ext_df3.appealCode)]
ext_df2_drop_appeal.appealCode.unique()

array([], dtype=object)

In [ ]:
ext_df3_drop_appeal = ext_df3[ext_df3.appealCode.isin(ext_df4.appealCode)]
ext_df3_drop_appeal.appealCode.unique()

array(['MDRMN020'], dtype=object)

In [ ]:
ext_df1_dropped = ext_df1[~ext_df1.appealCode.isin(ext_df2.appealCode)]
ext_df2_dropped = ext_df2[~ext_df2.appealCode.isin(ext_df3.appealCode)]
#ext_df3_dropped = ext_df3[~ext_df3.appealCode.isin(ext_df4.appealCode)]

#compare shapes
print(f"Dropped rows ext_df1: {ext_df1.shape[0] - ext_df1_dropped.shape[0]}")
print(f"Dropped rows ext_df2: {ext_df2.shape[0] - ext_df2_dropped.shape[0]}")
print(f"Dropped rows ext_df3: {ext_df3.shape[0] - ext_df3_dropped.shape[0]}")

Dropped rows ext_df1: 29
Dropped rows ext_df2: 0
Dropped rows ext_df3: 21

In [6]:
ext_df_cat = pd.concat([ext_df1 ,ext_df2, ext_df3])
ext_df_cat.appealCode.nunique()

718

In [9]:
ext_df_cat.to_csv(
    DATA_OUT_LLMS
    / f"0-717_latest_reports_1quali_chunksize1000_Noneit_meta-llama_llama-4-scout-17b-16e-instruct_v{dt.date.today().strftime('%d%m%y')}.csv",
    index=False,
)

In [10]:
ext_df_cat

,impactSubtype,impactValue,impactValueMin,impactValueMax,impactValuePrecision,impactUnit,valueAnnotation,valid_errors_impactValue,country,location,...,disasterType,nathaz_text,impacts,Mobility and Access to Transport,humanHealthAndWellbeing,impactsAnnotation,Earthquake,Wildfire,Drought,Conflict
0,Affected People,285300.0,NaN,NaN,exact,people,"['Between July and September 1995, unusually h...",0.0,"['Benin', 'Chad', 'Central African Republic', ...",NaN,...,Flood,"['BENIN, CHAD, CENTRAL AFRICAN REPUBLIC, MAURI...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Homeless People,285300.0,NaN,NaN,exact,people,['Most people lost both their homes and belong...,0.0,"['BENIN', 'CHAD', 'CENTRAL AFRICAN REPUBLIC', ...",NaN,...,Flood,"['BENIN, CHAD, CENTRAL AFRICAN REPUBLIC, MAURI...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Affected People,285300.0,NaN,NaN,exact,people,['CHAD MAURITANI A TOGO TOTAL Population Affec...,0.0,"['BENIN', 'CHAD', 'CENTRAL AFRICAN REPUBLIC', ...",NaN,...,Flood,"['BENIN, CHAD, CENTRAL AFRICAN REPUBLIC, MAURI...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Human Deaths,26.0,NaN,NaN,exact,people,['Loss of Life 20 - 2.00 - 4 26'],0.0,"['BENIN', 'CHAD', 'CENTRAL AFRICAN REPUBLIC', ...",NaN,...,Flood,"['BENIN, CHAD, CENTRAL AFRICAN REPUBLIC, MAURI...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Homeless People,167300.0,NaN,NaN,exact,people,"['Homeless 8,000 1,957 40,343 95,000 22,000 16...",0.0,"['BENIN', 'CHAD', 'CENTRAL AFRICAN REPUBLIC', ...",NaN,...,Flood,"['BENIN, CHAD, CENTRAL AFRICAN REPUBLIC, MAURI...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6090,Infected and Ill People,59088.0,NaN,NaN,exact,people,"[""The MoH's epi-week 44 report, released on No...",0.0,['Malawi'],"['Karonga', 'Rumphi', 'Mzimba North', 'Mzimba ...",...,Cholera,['FINAL OPERATION UPDATE Malawi | Tropical Cyc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6091,Human Deaths,1769.0,NaN,NaN,exact,people,"[""The MoH's epi-week 44 report, released on No...",0.0,['Malawi'],NaN,...,Cholera,['FINAL OPERATION UPDATE Malawi | Tropical Cyc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6092,Human Health and Wellbeing,3.0,NaN,NaN,exact,%,"[""The MoH's epi-week 44 report, released on No...",0.0,['Malawi'],['Malawi'],...,Cholera,['FINAL OPERATION UPDATE Malawi | Tropical Cyc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6093,"Access to Water, Sanitation, and Hygiene",14.0,NaN,NaN,exact,districts,['The OCV covered 14 high-risk districts namel...,0.0,['Malawi'],"['Karonga', 'Rumphi', 'Mzimba North', 'Mzimba ...",...,Cholera,['FINAL OPERATION UPDATE Malawi | Tropical Cyc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6094,Economy and Livelihood,NaN,NaN,NaN,NaN,NaN,"['A unified plan was developed, incorporating ...",0.0,['Malawi'],"['Blantyre', 'Phalombe', 'Mulanje', 'Chiradzul...",...,Cholera,['FINAL OPERATION UPDATE Malawi | Tropical Cyc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Check labelling

In [ ]:
#load processed reports
file_path = DATA_IN_JSONS / "retest2_new_sel_filtered_report_types_nat_hazards_bugfix_v180925.csv"#'all_ifrc_reports_info_processed_extended_format_nb_std_units.json' "nathaz_ifrc_reports_info_processed.json"
ifrc_reports_df = pd.read_csv(file_path)

In [ ]:
#select reports for which labelling has been done
from src.post_process_functions import format_output


labelled_reports = pd.read_csv(DATA_LABELLED / "labelled_reports_impacts_all_v160925.csv")

keys = labelled_reports[['appealCode', 'reportDate']].drop_duplicates()
test_reports = ifrc_reports_df.merge(keys, on=['appealCode', 'reportDate'], how='inner')
print(f"Nb. labeled reports: {len(labelled_reports.appealCode.unique())}, nb. found reports: {len(test_reports)}")
test_reports = format_output(test_reports, list_cols=["sentences","nathaz_text"])

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/lseverino/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt to /Users/lseverino/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/lseverino/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Nb. labeled reports: 25, nb. found reports: 25

In [ ]:
appeals_check = labelled_reports.appealCode.unique().tolist()#labelled_ana.appealCode.unique().tolist() + labelled_gabi.appealCode.unique().tolist() #+ labelled_laura.appealCode.unique() + labelled_luca.appealCode.unique()
iappeal = "MDRSV012"#appeals_check[24]
ireport = test_reports.loc[test_reports.appealCode==iappeal].iloc[0]
download_report(ireport, DATA_PDF)
labelled_reports.loc[labelled_reports.appealCode==iappeal]

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,annotation,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,appealCode,comments
127,2019-06-26,Affected People,NaN,NaN,NaN,NaN,NaN,['Situation analysis Description of the disast...,['El Salvador'],"['Morazn department', 'La Union department', '...",2019.0,10.0,7.0,NaN,NaN,NaN,"['Tropical storm', 'Flood', 'Mass Movement']",MDRSV012,NaN
128,2019-06-26,Road Infrastructure,24.0,highways,exact,NaN,NaN,['Situation analysis Description of the disast...,['El Salvador'],"['Morazn department', 'La Union department', '...",2019.0,10.0,7.0,NaN,NaN,NaN,"['Tropical storm', 'Flood', 'Mass Movement']",MDRSV012,NaN
129,2019-06-26,Road Infrastructure,31.0,roads,exact,NaN,NaN,['Situation analysis Description of the disast...,['El Salvador'],"['Morazn department', 'La Union department', '...",2019.0,10.0,7.0,NaN,NaN,NaN,"['Tropical storm', 'Flood', 'Mass Movement']",MDRSV012,NaN
130,2019-06-26,Injured People,14.0,people,exact,NaN,NaN,['Situation analysis Description of the disast...,['El Salvador'],"['Morazn department', 'La Union department', '...",2019.0,10.0,7.0,NaN,NaN,NaN,"['Tropical storm', 'Flood', 'Mass Movement']",MDRSV012,NaN
131,2019-06-26,Human Deaths,1.0,people,exact,NaN,NaN,['Situation analysis Description of the disast...,['El Salvador'],"['Morazn department', 'La Union department', '...",2019.0,10.0,7.0,NaN,NaN,NaN,"['Tropical storm', 'Flood', 'Mass Movement']",MDRSV012,NaN
132,2019-06-26,Crop Production and Forestry,42.0,trees,exact,NaN,NaN,['Situation analysis Description of the disast...,['El Salvador'],"['Morazn department', 'La Union department', '...",2019.0,10.0,7.0,NaN,NaN,NaN,"['Tropical storm', 'Flood', 'Mass Movement']",MDRSV012,NaN
133,2019-06-26,Residential Buildings,4.0,Affected homes,exact,NaN,NaN,['Situation analysis Description of the disast...,['El Salvador'],"['Morazn department', 'La Union department', '...",2019.0,10.0,7.0,NaN,NaN,NaN,"['Tropical storm', 'Flood', 'Mass Movement']",MDRSV012,NaN
134,2019-06-26,Residential Buildings,1409.0,Flooded homes,exact,NaN,NaN,['Situation analysis Description of the disast...,['El Salvador'],"['Morazn department', 'La Union department', '...",2019.0,10.0,7.0,NaN,NaN,NaN,"['Tropical storm', 'Flood', 'Mass Movement']",MDRSV012,NaN
135,2019-06-26,Residential Buildings,2.0,Destroyed homes,exact,NaN,NaN,['Situation analysis Description of the disast...,['El Salvador'],"['Morazn department', 'La Union department', '...",2019.0,10.0,7.0,NaN,NaN,NaN,"['Tropical storm', 'Flood', 'Mass Movement']",MDRSV012,NaN
136,2019-06-26,Informal settlements,13.0,shelters,exact,NaN,NaN,['Situation analysis Description of the disast...,['El Salvador'],"['Morazn department', 'La Union department', '...",2019.0,10.0,7.0,NaN,NaN,NaN,"['Tropical storm', 'Flood', 'Mass Movement']",MDRSV012,NaN

In [ ]:
print(iappeal)
ireport.nathaz_text

MDRSV012

['DREF Operation n° MDRSV012 GLIDE: n° TC-2018-000167-SLV Date of issue: 25 June 2019 Date of disaster: 15 October 2018 Operation start date: 1 December 2018 Operation end date: 15 February 2019 DREF allocated: 150,671 Swiss francs (CHF) Number of people affected: 7,085 (1,417 families) Number of people assisted: 2,090 (418 families) Host National Society presence (n° of volunteers, staff, branches): The Salvadorean Red Cross Society (SRCS) has one headquarter, 63 branches throughout the country, 2,239 volunteers and 275 staff.',
 '75 volunteers have been trained as National Intervention Teams (NITs) with different specialties (Water, Sanitation and Hygiene Promotion, Logistics, General, ZIKA and Vector Control, Psychosocial Support (PSS)) and 35 active volunteers trained in the Damage Assessment and Needs Analysis (DANA) assessment tool.',
 'Red Cross Red Crescent Movement partners actively involved in the operation: International Federation of Red Cross and Red Crescent Societies (IFRC).',
 'Other partner organizations actively involved in the operation: El Salvador Civil Protection System and departmental, municipal and community commissions, Ministry of Health, the Medical Emergency System (SEM for its acronym in Spanish), the Solidarity Fund for Health (FOSALUD for its acronym in Spanish), National Administration of Aqueducts and Sewers (ANDA), Municipal Mayors’ Offices, Ministry of Education, Departmental, Municipal and Community Civil Protection Commissions, Health Committees in communities, and ADESCOS.',
 'The major donors and partners of the Disaster Relief Emergency Fund (DREF) include the Red Cross Societies and governments of Belgium, Britain, Canada, Denmark, German, Ireland, Italy, Japan, Luxembourg, New Zealand, Norway, Republic of Korea, Spain, Sweden and Switzerland, as well as DG ECHO and Blizzard Entertainment, Mondelez International Foundation, and Fortive Corporation and other corporate and private donors.',
 'The IFRC, on behalf of the national society, would like to extend thanks to all for their generous contributions.',
 'ECHO and the government of Canada have replenished the DREF in the occasion of this operation.',
 'The total amount spent under this DREF operation was 118,630 CHF.',
 'The remaining balance of 32,041 CHF will be reimbursed to the Disaster Relief Emergency Fund.',
 '< For the Final Financial Report, click here.',
 'For contact information, click here.',
 '> A.',
 'Situation analysis Description of the disaster On 6 October, rains began falling over eastern El Salvador due to the influence of tropical depression No.',
 '14 located near the Honduran Atlantic coast.',
 'On 7 October, the tropical depression was upgraded to Tropical Storm Michael, which continued moving north over the Yucatán channel toward the System declared a Green Alert for the entire country.',
 'On 7 October, a Yellow Alert was declared for 29 coastal municipalities, which on 8 October increased to 34 municipalities to include three municipalities in Morazán department and two in La Union department.',
 'A Green Alert remained in place for the rest of the country.',
 'The rains have affected the entire country.',
 'The hardest hit have been the eastern regions, specifically the cantons of El Brazo, La Canoa and El Tecomatal in the municipality of San Miguel; the cantons of San Felipe and Las Tunas in La Unión department; the cantons of Capitán Lazo and Puerto Parada in the municipality of Usulután; as well as the canton of Metalío in Sonsonate department (western El Salvador) and the DREF Final Report El Salvador: Floods Photo: Area affected by Hurricane Michael.',
 'Source: SRCS 2019.',
 '2 | P a g e cantons of San Diego and San Rafael Abajo in the municipality of La Libertad in central El Salvador.',
 "These floods affected most municipalities located along the country's coast.",
 'Report on the effects of the National Civil Protection System Event: Yellow and green warning for rain 11:30 AM 06/10/2018 Preliminary report accumulated no.',
 '3, affectations from 16:30 hours on 05/10/2018 to 06:00 hours on 09/10/2018.']

In [ ]:
from importlib import reload
from src import text_processing_functions
reload(text_processing_functions)
from src.text_processing_functions import select_impact_description
select_impact_description(ireport.sentences)

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/lseverino/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt to /Users/lseverino/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/lseverino/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

['DREF Operation n° MDRSV012 GLIDE: n° TC-2018-000167-SLV Date of issue: 25 June 2019 Date of disaster: 15 October 2018 Operation start date: 1 December 2018 Operation end date: 15 February 2019 DREF allocated: 150,671 Swiss francs (CHF) Number of people affected: 7,085 (1,417 families) Number of people assisted: 2,090 (418 families) Host National Society presence (n° of volunteers, staff, branches): The Salvadorean Red Cross Society (SRCS) has one headquarter, 63 branches throughout the country, 2,239 volunteers and 275 staff.',
 '75 volunteers have been trained as National Intervention Teams (NITs) with different specialties (Water, Sanitation and Hygiene Promotion, Logistics, General, ZIKA and Vector Control, Psychosocial Support (PSS)) and 35 active volunteers trained in the Damage Assessment and Needs Analysis (DANA) assessment tool.',
 'Red Cross Red Crescent Movement partners actively involved in the operation: International Federation of Red Cross and Red Crescent Societies (IFRC).',
 'Other partner organizations actively involved in the operation: El Salvador Civil Protection System and departmental, municipal and community commissions, Ministry of Health, the Medical Emergency System (SEM for its acronym in Spanish), the Solidarity Fund for Health (FOSALUD for its acronym in Spanish), National Administration of Aqueducts and Sewers (ANDA), Municipal Mayors’ Offices, Ministry of Education, Departmental, Municipal and Community Civil Protection Commissions, Health Committees in communities, and ADESCOS.',
 'The major donors and partners of the Disaster Relief Emergency Fund (DREF) include the Red Cross Societies and governments of Belgium, Britain, Canada, Denmark, German, Ireland, Italy, Japan, Luxembourg, New Zealand, Norway, Republic of Korea, Spain, Sweden and Switzerland, as well as DG ECHO and Blizzard Entertainment, Mondelez International Foundation, and Fortive Corporation and other corporate and private donors.',
 'The IFRC, on behalf of the national society, would like to extend thanks to all for their generous contributions.',
 'ECHO and the government of Canada have replenished the DREF in the occasion of this operation.',
 'The total amount spent under this DREF operation was 118,630 CHF.',
 'The remaining balance of 32,041 CHF will be reimbursed to the Disaster Relief Emergency Fund.',
 '< For the Final Financial Report, click here.',
 'For contact information, click here.',
 '> A.',
 'Situation analysis Description of the disaster On 6 October, rains began falling over eastern El Salvador due to the influence of tropical depression No.',
 '14 located near the Honduran Atlantic coast.',
 'On 7 October, the tropical depression was upgraded to Tropical Storm Michael, which continued moving north over the Yucatán channel toward the System declared a Green Alert for the entire country.',
 'On 7 October, a Yellow Alert was declared for 29 coastal municipalities, which on 8 October increased to 34 municipalities to include three municipalities in Morazán department and two in La Union department.',
 'A Green Alert remained in place for the rest of the country.',
 'The rains have affected the entire country.',
 'The hardest hit have been the eastern regions, specifically the cantons of El Brazo, La Canoa and El Tecomatal in the municipality of San Miguel; the cantons of San Felipe and Las Tunas in La Unión department; the cantons of Capitán Lazo and Puerto Parada in the municipality of Usulután; as well as the canton of Metalío in Sonsonate department (western El Salvador) and the DREF Final Report El Salvador: Floods Photo: Area affected by Hurricane Michael.',
 'Source: SRCS 2019.',
 '2 | P a g e cantons of San Diego and San Rafael Abajo in the municipality of La Libertad in central El Salvador.',
 "These floods affected most municipalities located along the country's coast.",
 'Report on the effects of the National Civil Protection System Event: Yellow and green warning for rain 11:30 AM 06/10/2018 Preliminary report accumulated no.',
 '3, affectations from 16:30 hours on 05/10/2018 to 06:00 hours on 09/10/2018.',
 'Affected transit routes TOTAL Flooded highways 1 Flooded roads 3 Affected highways 24 Affected rods 31 Isolated communities 1 Affected people TOTAL Injured 14 Dead 4 Sheltered 1,090 Active shelters 13 Other TOTAL Fallen trees 42 Branches of fallen trees 5 Landslides 74 Floods 1 Overflowed rivers 7 Subsidences 1 Vehicles directly affected by the event 5 Affected homes and buildings TOTAL Affected homes 6 Flooded homes 1,409 Destroyed homes 2 Other buildings affected 1 Other buildings destroyed (collapsed walls) 6 Summary of response Overview of Host National Society The Salvadorean Red Cross Society (SRCS) constantly monitored the situation through its branches across the country since the onset of low-pressure system No.']