In [29]:
import pandas as pd
import datetime as dt
import os
import pathlib
from src.data import *
from src.labelling_helpers import *

In [30]:
# load all reports containing mdr in filename
report_dir = pathlib.Path(DATA_LABELLED / "v260626")
mdr_paths = list(report_dir.rglob("*MDR*.csv"))

In [31]:
mdr_reports = pd.concat([pd.read_csv(path) for path in mdr_paths], ignore_index=True)

In [32]:
mdr_reports.appealCode.nunique()

19

In [33]:
mdr_reports

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,annotation,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,appealCode,comments
0,2022-08-03,Affected People,76790.0,people,approx,NaN,NaN,"[""P a g e 1 Internal DREF Operation n MDRYE011...",['Yemen'],"['Marib', 'Al Mahwit', 'Taiz', 'Ibb', 'Hadrama...",2022.0,7.0,23.0,NaN,NaN,NaN,['Flood'],MDRYE011,NaN
1,2022-08-03,Residential Buildings,NaN,NaN,NaN,NaN,NaN,"[""Situation analysis Description of the disast...",['Yemen'],['Sanaa governorate'],2022.0,7.0,23.0,NaN,NaN,NaN,['Flood'],MDRYE011,NaN
2,2022-08-03,Informal settlements,NaN,NaN,NaN,NaN,NaN,"[""Situation analysis Description of the disast...",['Yemen'],['Sanaa governorate'],2022.0,7.0,23.0,NaN,NaN,NaN,['Flood'],MDRYE011,NaN
3,2022-08-03,Displaced People,NaN,NaN,NaN,NaN,NaN,"[""Situation analysis Description of the disast...",['Yemen'],['Sanaa governorate'],2022.0,7.0,23.0,NaN,NaN,NaN,['Flood'],MDRYE011,NaN
4,2022-08-03,Human Deaths,3.0,people,exact,NaN,NaN,"[""Situation analysis Description of the disast...",['Yemen'],['Sanaa governorate'],2022.0,7.0,23.0,NaN,NaN,NaN,['Flood'],MDRYE011,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
424,2021-12-27,Human Deaths,14.0,people,exact,NaN,NaN,['According to the Kurdish region government o...,['Iraq'],['Kurdish region'],2021.0,12.0,17.0,2021.0,12.0,19.0,"['Flood', 'Drought']",MDRIQ014,NaN
425,2021-12-27,Affected People,NaN,people,approx,7000.0,7500.0,['According to the Kurdish region government o...,['Iraq'],['Kurdish region'],2021.0,12.0,17.0,2021.0,12.0,19.0,"['Flood', 'Drought']",MDRIQ014,NaN
426,2021-12-27,Missing People,NaN,NaN,NaN,NaN,NaN,['More are feared missing while search and res...,['Iraq'],['Kurdish region'],2021.0,12.0,17.0,2021.0,12.0,19.0,['Flood'],MDRIQ014,NaN
427,2021-12-27,Affected People,7000000.0,people,approx,NaN,NaN,['The dis astrous heavy rains came at a time w...,['Iraq'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Drought'],MDRIQ014,NaN
428,2021-12-27,Crop Production and Forestry,NaN,NaN,NaN,NaN,NaN,['The dis astrous heavy rains came at a time w...,['Iraq'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Drought'],MDRIQ014,NaN

In [34]:
# other reports
luca = pd.read_csv(report_dir / "labelled_reports_impacts_luca_gaps_v260626.csv")
cecily = pd.read_csv(report_dir / "red_crosslabelled_reports_cecily.csv")
ana = pd.read_csv(report_dir / "labelled_reports_round2_ANA.csv")
gabi = pd.read_csv(report_dir / "labelled_reports_round2_Gabriela.csv")

In [35]:
luca

,reportDate,impactSubType,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,annotation,comments,appealCode
0,2024-09-22,Affected People,11100.0,people,exact,NaN,NaN,['Algeria'],"['Béchar', 'Elbayadh', 'Beni Abbes', 'Tamanras...",2024.0,9.0,5.0,2024.0,9.0,8.0,['Flood'],['DREF Operation Algeria Flood 2024 Bechar App...,NaN,MDRDZ011
1,2024-09-22,Displaced People,2280.0,families,approx,2280.0,NaN,['Algeria'],"['Béchar', 'Elbayadh', 'Beni Abbes', 'Tamanras...",2024.0,9.0,5.0,2024.0,9.0,8.0,['Flood'],['DREF Operation Algeria Flood 2024 Bechar App...,NaN,MDRDZ011
2,2024-09-22,Undefined Infrastructure,NaN,critical infrastructure,approx,NaN,NaN,['Algeria'],"['Béchar', 'Elbayadh', 'Beni Abbes', 'Tamanras...",2024.0,9.0,5.0,2024.0,9.0,8.0,['Flood'],['DREF Operation Algeria Flood 2024 Bechar App...,NaN,MDRDZ011
3,2024-09-22,Displaced People,2060.0,families,approx,NaN,2060.0,['Algeria'],['Béchar'],2024.0,9.0,5.0,2024.0,9.0,8.0,['Flood'],['DREF Operation Algeria Flood 2024 Bechar App...,NaN,MDRDZ011
4,2024-09-22,Road Infrastructure,4.0,bridges,approx,4.0,NaN,['Algeria'],['Béchar'],2024.0,9.0,5.0,2024.0,9.0,8.0,['Flood'],['DREF Operation Algeria Flood 2024 Bechar App...,NaN,MDRDZ011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,2024-10-02,Crop Production and Forestry,NaN,NaN,approx,NaN,NaN,['Mozambique'],[],2024.0,3.0,NaN,NaN,NaN,NaN,['Tropical storm'],['1 OPERATION UPDATE Mozambique | Drought Emer...,NaN,MDRMZ024
216,2024-10-02,Other Service Access Impacts,NaN,NaN,approx,NaN,NaN,['Mozambique'],[],2024.0,3.0,NaN,NaN,NaN,NaN,"['Drought', 'Tropical storm']",['1 OPERATION UPDATE Mozambique | Drought Emer...,NaN,MDRMZ024
217,2024-10-02,Crop Production and Forestry,690000.0,hectares of crops,exact,NaN,NaN,['Mozambique'],"['Tete', 'Gaza', 'Manica', 'Inhambane']",2024.0,3.0,NaN,2024.0,4.0,NaN,"['Drought', 'Tropical storm']",['1 OPERATION UPDATE Mozambique | Drought Emer...,NaN,MDRMZ024
218,2024-10-02,Access to Food,2700000.0,people,NaN,NaN,NaN,['Mozambique'],[],2024.0,NaN,NaN,2024.0,7.0,NaN,"['Drought', 'Tropical storm']",['1 OPERATION UPDATE Mozambique | Drought Emer...,NaN,MDRMZ024
219,2024-10-02,Other Economic and Livelihood Impacts,3.0,\% inflation rate,NaN,NaN,NaN,['Mozambique'],[],2024.0,NaN,NaN,2024.0,6.0,NaN,"['Drought', 'Tropical storm']",['1 OPERATION UPDATE Mozambique | Drought Emer...,NaN,MDRMZ024

In [36]:
luca.appealCode.nunique()

7

In [37]:
cecily

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,annotation,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,comments,appealCode
0,2023-10-23,Affected People,2000.0,people,exact,NaN,NaN,['DREF OPERATION Cameroon_Landslide Appeal: Co...,['Cameroon'],NaN,2023,10,8,2024.0,1.0,31.0,['Mass movement'],NaN,MDRCM036
1,2023-10-23,Targeted People,700.0,people,exact,NaN,NaN,['DREF OPERATION Cameroon_Landslide Appeal: Co...,['Cameroon'],NaN,2023,10,8,2024.0,1.0,31.0,['Mass movement'],NaN,MDRCM036
2,2023-10-23,DREF Allocation & Funding requirements,61882.0,CHF,exact,NaN,NaN,['DREF OPERATION Cameroon_Landslide Appeal: Co...,['Cameroon'],NaN,2023,10,8,2024.0,1.0,31.0,['Mass movement'],NaN,MDRCM036
3,2023-10-23,Affected People,NaN,people,approx,700.0,NaN,['The Red Cross volunteers who were quickly de...,['Cameroon'],['Mbankolo neighborhood'],2023,10,8,NaN,NaN,NaN,['Mass movement'],NaN,MDRCM036
4,2023-10-23,Affect People,NaN,households,approx,NaN,110.0,['The Red Cross volunteers who were quickly de...,['Cameroon'],['Mbankolo neighborhood'],2023,10,8,NaN,NaN,NaN,['Mass movement'],NaN,MDRCM036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,2025-06-17,Access to Healthcare,NaN,NaN,NaN,NaN,NaN,"['Additionally, many affected individuals lack...",['Jordan'],"['Ajloun', 'Karak', 'Mafraq', 'Amman', 'Taleh'...",2023,11,19,NaN,NaN,NaN,['Extreme cold temperature'],NaN,MDRJO003
63,2025-06-17,Mobility and Access to Transport,NaN,NaN,NaN,NaN,NaN,['The affected areas had very limited services...,['Jordan'],"['Ajloun', 'Karak', 'Mafraq', 'Amman', 'Taleh'...",2023,11,19,NaN,NaN,NaN,['Extreme cold temperature'],NaN,MDRJO003
64,2025-06-17,Undefined Service Access,NaN,NaN,NaN,NaN,NaN,['The affected areas had very limited services...,['Jordan'],"['Ajloun', 'Karak', 'Mafraq', 'Amman', 'Taleh'...",2023,11,19,NaN,NaN,NaN,['Extreme cold temperature'],NaN,MDRJO003
65,2025-06-17,Access to Food,NaN,NaN,NaN,NaN,NaN,['This directly impacted their ability to secu...,['Jordan'],"['Ajloun', 'Karak', 'Mafraq', 'Amman', 'Taleh'...",2023,11,19,NaN,NaN,NaN,['Extreme cold temperature'],NaN,MDRJO003
66,2025-06-17,"Access to Water, Sanitation, and Hygiene",NaN,NaN,NaN,NaN,NaN,"['Water, Sanitation And Hygiene As mentioned u...",['Jordan'],"['Ajloun', 'Karak', 'Mafraq', 'Amman', 'Taleh'...",2023,11,19,NaN,NaN,NaN,['Extreme cold temperature'],NaN,MDRJO003

In [38]:
cecily.appealCode.nunique()

4

In [39]:
ana

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,annotation,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,appealCode,impactSubType
0,2016-03-31,Affected People,247408.0,people,exact,NaN,NaN,"['Number of people affected: 247,408 Estimated...","['Vanuatu', 'Papua New Guinea', 'Tuvalu', 'Sol...",NaN,2015.0,3.0,13.0,2017.0,9.0,30.0,['Tropical storm'],MDR55001,NaN
1,2016-03-31,Assisted People,43880.0,people,exact,NaN,NaN,"['An estimated revised 43,880 people have been...","['Vanuatu', 'Papua New Guinea', 'Tuvalu', 'Sol...",NaN,2015.0,3.0,13.0,2017.0,9.0,30.0,['Tropical storm'],MDR55001,NaN
2,2016-03-31,Assisted People,39915.0,people,exact,NaN,NaN,"['An estimated revised 43,880 people have been...",['Vanuatu'],['Vanuatu'],2015.0,3.0,13.0,2017.0,9.0,30.0,['Tropical storm'],MDR55001,NaN
3,2016-03-31,Targeted People,34573.0,people,exact,NaN,NaN,"['The final estimation of 34,573 beneficiaries...","['Vanuatu', 'Papua New Guinea', 'Tuvalu', 'Sol...",NaN,2015.0,3.0,13.0,2017.0,9.0,30.0,['Tropical storm'],MDR55001,NaN
4,2016-03-31,DREF Allocation & Funding requirements,8024577.0,CHF,exact,NaN,NaN,"['Appeal budget (revised): CHF 8,024,577 Curre...","['Vanuatu', 'Papua New Guinea', 'Tuvalu', 'Sol...",NaN,2015.0,3.0,13.0,2017.0,9.0,30.0,['Tropical storm'],MDR55001,NaN
5,2016-03-31,Education Infrastructure,3.0,education infrastructure,exact,NaN,NaN,['Two out of three schools rehabilitations hav...,['Vanuatu'],['Emae Island'],2015.0,3.0,13.0,2017.0,9.0,30.0,['Tropical storm'],MDR55001,NaN
6,2025-12-08,DREF Allocation & Funding requirements,499885.0,CHF,exact,NaN,NaN,['Appeal: Total DREF Allocation: Crisis Catego...,['Afghanistan'],NaN,2024.0,3.0,16.0,2024.0,7.0,31.0,['Extreme cold temperature'],MDRAF014,NaN
7,2025-12-08,Affected People,325205.0,people,approx,NaN,NaN,['Further assessments highlighted the extensiv...,['Afghanistan'],NaN,2024.0,3.0,16.0,2024.0,7.0,31.0,['Extreme cold temperature'],MDRAF014,NaN
8,2025-12-08,Targeted People,22400.0,people,exact,NaN,NaN,['Appeal: Total DREF Allocation: Crisis Catego...,['Afghanistan'],NaN,2024.0,3.0,16.0,2024.0,7.0,31.0,['Extreme cold temperature'],MDRAF014,NaN
9,2025-12-08,Human Deaths,25.0,people,exact,NaN,NaN,"['Nuristan was particularly affected, still re...",['Afghanistan'],['Nuristan'],NaN,NaN,NaN,NaN,NaN,NaN,['Mass movement'],MDRAF014,NaN
10,2025-12-08,Residential Buildings,20.0,houses destroyed,exact,NaN,NaN,"['Nuristan was particularly affected, still re...",['Afghanistan'],['Nuristan'],NaN,NaN,NaN,NaN,NaN,NaN,['Mass movement'],MDRAF014,NaN
11,2025-12-08,Displaced People,1050.0,people,approx,NaN,NaN,"['Nuristan was particularly affected, still re...",['Afghanistan'],['Nuristan'],NaN,NaN,NaN,NaN,NaN,NaN,['Mass movement'],MDRAF014,NaN
12,2025-12-08,Affected Livestock and Animals,NaN,affected animals,approx,70000.0,NaN,['ECHO reported temperatures plummeting to -33...,['Afghanistan'],['Ghor'],2024.0,3.0,16.0,2024.0,7.0,31.0,['Extreme cold temperature'],MDRAF014,NaN
13,2025-12-08,Human Deaths,70.0,people,exact,NaN,NaN,['ECHO reported temperatures plummeting to -33...,['Afghanistan'],['Ghor'],2024.0,3.0,16.0,2024.0,7.0,31.0,['Extreme cold temperature'],MDRAF014,NaN
14,2025-12-08,Human Deaths,NaN,people,approx,1197.0,NaN,"['The toll included over 1,197 deaths, 2,217 i...",['Afghanistan'],NaN,2024.0,3.0,16.0,2024.0,7.0,31.0,['Extreme cold temperature'],MDRAF014,NaN
15,2025-12-08,Injured People,2217.0,people,exact,NaN,NaN,"['The toll included over 1,197 deaths, 2,217 i...",['Afghanistan'],NaN,2024.0,3.0,16.0,2024.0,7.0,31.0,['Extreme cold temperature'],MDRAF014,NaN
16,2025-12-08,Crop Production and Forestry,NaN,NaN,NaN,NaN,NaN,"['The toll included over 1,197 deaths, 2,217 i...",['Afghanistan'],NaN,2024.0,3.0,16.0,2024.0,7.0,31.0,['Extreme cold temperature'],MDRAF014,NaN
17,2025-12-08,Affected Livestock and Animals,NaN,NaN,NaN,NaN,NaN,['Thousands of livestock losses were also reco...,['Afghanistan'],NaN,2024.0,3.0,16.0,2024.0,7.0,31.0,['Extreme cold temperature'],MDRAF014,NaN
18,2025-12-08,Road Infrastructure,NaN,NaN,NaN,NaN,NaN,['Reports indicated that high-altitude provinc...,['Afghanistan'],NaN,2024.0,3.0,16.0,2024.0,7.0,31.0,['Extreme cold temperature'],MDRAF014,NaN
19,2025-12-08,Economy and Livelihood,NaN,NaN,NaN,NaN,NaN,['Reports indicated that high-altitude provinc...,['Afghanistan'],NaN,2024.0,3.0,16.0,2024.0,7.0,31.0,['Extreme cold temperature'],MDRAF014,NaN
20,2025-12-08,DREF Allocation & Funding requirements,496034.0,CHF,exact,NaN,NaN,['Appeal: Total DREF Allocation Crisis Categor...,['Colombia'],NaN,2023.0,4.0,14.0,2023.0,9.0,30.0,"['Volcanic activity', 'Earthquake']",MDRCO023,NaN
21,2025-12-08,Targeted People,15314.0,people,exact,NaN,NaN,['Appeal: Total DREF Allocation Crisis Categor...,['Colombia'],NaN,2023.0,4.0,14.0,2023.0,9.0,30.0,"['Volcanic activity', 'Earthquake']",MDRCO023,NaN
22,2025-12-08,Displaced People,102.0,people,exact,NaN,NaN,"['The decision was taken because, of an evacua...",['Colombia'],NaN,2023.0,4.0,13.0,2023.0,9.0,30.0,"['Volcanic activity', 'Earthquake']",MDRCO023,NaN
23,2025-12-08,DREF Allocation & Funding requirements,273597.0,CHF,exact,NaN,NaN,"['In response to the situation, the IFRC launc...",['Guinea-Bissau'],NaN,2018.0,7.0,9.0,2018.0,12.0,9.0,['Other storm'],MDRGW003,NaN
24,2025-12-08,Affected People,11541.0,people,exact,NaN,NaN,['According to the Civil Protections initial p...,['Guinea-Bissau'],['Bissau (Autonomous Sector of Bissau)'],2018.0,6.0,27.0,2018.0,12.0,9.0,['Other storm'],MDRGW003,NaN
25,2025-12-08,Displaced People,800.0,people,exact,NaN,NaN,['Three (3) deaths were also reported and 800 ...,['Guinea-Bissau'],['Bissau (Autonomous Sector of Bissau)'],2018.0,6.0,27.0,2018.0,12.0,9.0,['Other storm'],MDRGW003,NaN
26,2025-12-08,Human Deaths,3.0,people,exact,NaN,NaN,['Three (3) deaths were also reported and 800 ...,['Guinea-Bissau'],['Bissau (Autonomous Sector of Bissau)'],2018.0,6.0,27.0,2018.0,12.0,9.0,['Other storm'],MDRGW003,NaN
27,2025-12-08,Residential Buildings,420.0,houses destroyed,exact,NaN,NaN,['According to the Civil Protections initial p...,['Guinea-Bissau'],['Bissau (Autonomous Sector of Bissau)'],2018.0,6.0,27.0,2018.0,12.0,9.0,['Other storm'],MDRGW003,NaN
28,2025-12-08,Residential Buildings,336.0,houses damaged,exact,NaN,NaN,['The initial assessment conducted between 28 ...,['Guinea-Bissau'],"['Bissau (Autonomous Sector of Bissau)', 'Antu...",2018.0,6.0,27.0,2018.0,12.0,9.0,['Other storm'],MDRGW003,NaN
29,2025-12-08,Education Infrastructure,37.0,education infrastructure,exact,NaN,NaN,['SITUATION ANALYSIS Description of the disast...,['Guinea-Bissau'],['Bissau (Autonomous Sector of Bissau)'],2018.0,6.0,27.0,2018.0,12.0,9.0,['Other storm'],MDRGW003,NaN
30,2025-12-08,Assisted People,3374.0,people,exact,NaN,NaN,"['Number of people assisted: 3,374 (303 househ...",['Guinea-Bissau'],NaN,2018.0,7.0,9.0,2018.0,12.0,9.0,['Other storm'],MDRGW003,NaN
31,2016-11-29,NaN,NaN,houses damaged,approx,750.0,NaN,"['On 21 June 2016, heavy rain and hailstorm hi...",['Hungary'],['Szabolcs-Szatmr-Bereg County'],2016.0,6.0,21.0,2016.0,8.0,29.0,['Storm'],MDRHU005,Residential Buildings
32,2016-11-29,NaN,NaN,people,approx,NaN,2282.0,['Emergency Plan of Action Final Report Hungar...,['Hungary'],['Szabolcs-Szatmr-Bereg County'],2016.0,6.0,21.0,2016.0,8.0,29.0,['Storm'],MDRHU005,Affected People
33,2016-11-29,NaN,610.0,people,approx,NaN,NaN,['Emergency Plan of Action Final Report Hungar...,['Hungary'],['Szabolcs-Szatmr-Bereg County'],2016.0,6.0,21.0,2016.0,8.0,29.0,['Storm'],MDRHU005,Assisted People
34,2016-11-29,NaN,46642.0,CHF,exact,NaN,NaN,['Emergency Plan of Action Final Report Hungar...,['Hungary'],['Szabolcs-Szatmr-Bereg County'],2016.0,6.0,21.0,2016.0,8.0,29.0,['Storm'],MDRHU005,DREF Allocation & Funding requirements

In [40]:
ana.appealCode.nunique()

5

In [41]:
gabi

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,annotation,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,appealCode
0,2025-12-08,Affected People,409115.0,people,exact,NaN,NaN,['Appeal: Total DREF Allocation Crisis Categor...,['Uruguay'],"['Cerro Largo', 'Florida', 'Lavalleja', 'San J...",2023.0,1.0,29.0,2023.0,8.0,31.0,['Drought'],MDRUY004
1,2025-12-08,Targeted People,12000.0,people,exact,NaN,NaN,['Appeal: Total DREF Allocation Crisis Categor...,['Uruguay'],"['Cerro Largo', 'Florida', 'Lavalleja', 'San J...",2023.0,1.0,29.0,2023.0,8.0,31.0,['Drought'],MDRUY004
2,2025-12-08,DREF Allocation & Funding requirements,381390.0,CHF,exact,NaN,NaN,['Appeal: Total DREF Allocation Crisis Categor...,['Uruguay'],"['Cerro Largo', 'Florida', 'Lavalleja', 'San J...",2023.0,1.0,29.0,2023.0,8.0,31.0,['Drought'],MDRUY004
3,2025-12-08,Water Quality and Availability,NaN,NaN,NaN,NaN,NaN,['The lack of rainfall since September 2022 ha...,['Uruguay'],"['Cerro Largo', 'Florida', 'Lavalleja', 'San J...",2023.0,1.0,29.0,2023.0,8.0,31.0,['Drought'],MDRUY004
4,2025-12-08,Economy and Livelihood,NaN,NaN,NaN,NaN,NaN,"['In addition, it was estimated that approxima...",['Uruguay'],"['Cerro Largo', 'Florida', 'Lavalleja', 'San J...",2023.0,1.0,29.0,2023.0,8.0,31.0,['Drought'],MDRUY004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,2025-02-05,Economy and Livelihood,NaN,NaN,NaN,NaN,NaN,"['By mid-2025, recovery was underway but remai...",['Vanuatu'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Earthquake'],MDRVU012
68,2025-02-05,Residential Buildings,NaN,NaN,NaN,NaN,NaN,['Many households continued living in damaged ...,['Vanuatu'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Earthquake'],MDRVU012
69,2025-02-05,Undefined Infrastructure,NaN,NaN,NaN,NaN,NaN,['Many households continued living in damaged ...,['Vanuatu'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Earthquake'],MDRVU012
70,2025-02-05,"Water, Sanitation, and Hygiene Infrastructure",NaN,NaN,NaN,NaN,NaN,"['By this period, reconstruction of damaged ho...",['Vanuatu'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Earthquake'],MDRVU012
71,2025-02-05,Education Infrastructure,NaN,NaN,NaN,NaN,NaN,"['By this period, reconstruction of damaged ho...",['Vanuatu'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Earthquake'],MDRVU012

In [42]:
gabi.appealCode.nunique()

5

In [43]:
# concatenate all labelled reports
labelled_reports_all = pd.concat([mdr_reports, luca, cecily, ana, gabi], axis=0, ignore_index=True)

In [44]:
labelled_reports_all

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,annotation,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,appealCode,comments,impactSubType
0,2022-08-03,Affected People,76790.0,people,approx,NaN,NaN,"[""P a g e 1 Internal DREF Operation n MDRYE011...",['Yemen'],"['Marib', 'Al Mahwit', 'Taiz', 'Ibb', 'Hadrama...",2022.0,7.0,23.0,NaN,NaN,NaN,['Flood'],MDRYE011,NaN,NaN
1,2022-08-03,Residential Buildings,NaN,NaN,NaN,NaN,NaN,"[""Situation analysis Description of the disast...",['Yemen'],['Sanaa governorate'],2022.0,7.0,23.0,NaN,NaN,NaN,['Flood'],MDRYE011,NaN,NaN
2,2022-08-03,Informal settlements,NaN,NaN,NaN,NaN,NaN,"[""Situation analysis Description of the disast...",['Yemen'],['Sanaa governorate'],2022.0,7.0,23.0,NaN,NaN,NaN,['Flood'],MDRYE011,NaN,NaN
3,2022-08-03,Displaced People,NaN,NaN,NaN,NaN,NaN,"[""Situation analysis Description of the disast...",['Yemen'],['Sanaa governorate'],2022.0,7.0,23.0,NaN,NaN,NaN,['Flood'],MDRYE011,NaN,NaN
4,2022-08-03,Human Deaths,3.0,people,exact,NaN,NaN,"[""Situation analysis Description of the disast...",['Yemen'],['Sanaa governorate'],2022.0,7.0,23.0,NaN,NaN,NaN,['Flood'],MDRYE011,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,2025-02-05,Economy and Livelihood,NaN,NaN,NaN,NaN,NaN,"['By mid-2025, recovery was underway but remai...",['Vanuatu'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Earthquake'],MDRVU012,NaN,NaN
819,2025-02-05,Residential Buildings,NaN,NaN,NaN,NaN,NaN,['Many households continued living in damaged ...,['Vanuatu'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Earthquake'],MDRVU012,NaN,NaN
820,2025-02-05,Undefined Infrastructure,NaN,NaN,NaN,NaN,NaN,['Many households continued living in damaged ...,['Vanuatu'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Earthquake'],MDRVU012,NaN,NaN
821,2025-02-05,"Water, Sanitation, and Hygiene Infrastructure",NaN,NaN,NaN,NaN,NaN,"['By this period, reconstruction of damaged ho...",['Vanuatu'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Earthquake'],MDRVU012,NaN,NaN
822,2025-02-05,Education Infrastructure,NaN,NaN,NaN,NaN,NaN,"['By this period, reconstruction of damaged ho...",['Vanuatu'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,['Earthquake'],MDRVU012,NaN,NaN

In [45]:
labelled_reports_all.appealCode.nunique()

39

In [46]:
# check missing appeals
appeal_codes = [
    "MDRDZ011",
    "MDRPK026",
    "MDRCM039",
    "MDRBJ019",
    "MDRSD034",
    "MDRNG041",
    "MDRRW022",
    "MDRZM022",
    "MDRUG050",
    "MDRMZ024",
    "MDRIR009",
    "MDRTP004",
    "MDRVU012",
    "MDRDZ007",
    "MDRAF014",
    "MDRCM036",
    "MDRDZ008",
    "MDRPH036",
    "MDRHT018",
    "MDRID013",
    "MDR55001",
    "MDRJO003",
    "MDRLB013",
    "MDRPK018",
    "MDRTJ035",
    "MDRCN006",
    "MDRBD022",
    "MDRYE011",
    "MDRS2001",
    "MDRIQ014",
    "MDRGN015",
    "MDRSV012",
    "MDRMY003",
    "MDRBD015",
    "MDRKE058",
    "MDRCO023",
    "MDRGW003",
    "MDRHU005",
    "MDRPH021",
    "MDRRS015",
    "MDRMN017",
    "MDRGT009",
    "MDRPG008",
    "MDREC019",
    "MDRTN010",
    "MDRCR012",
    "MDRGE019",
    "MDRKZ010",
    "MDRUY004",
]
appeals_missing = [
    code
    for code in appeal_codes
    if code not in labelled_reports_all.appealCode.unique()
]

In [47]:
appeals_missing

['MDRTP004',
 'MDRDZ007',
 'MDRHT018',
 'MDRGN015',
 'MDRBD015',
 'MDRPH021',
 'MDRGT009',
 'MDRTN010',
 'MDRCR012',
 'MDRGE019']

In [48]:
def reformat_date(x):
    xsplit = x.split(" ") # remove time if present
    date = xsplit[0]  # keep only the date part
    if "/" in date:
        day, month, year = date.split("/")
        return f"{year}-{month}-{day}"
    else:
        return date
labelled_reports_all["reportDate_orig"] = labelled_reports_all.reportDate
labelled_reports_all.reportDate = labelled_reports_all.reportDate.apply(reformat_date)
labelled_reports_all.reportDate = pd.to_datetime(labelled_reports_all.reportDate, errors="raise")

In [49]:
labelled_reports_all[["reportDate_orig", "reportDate"]].groupby("reportDate").head(1)

         reportDate_orig reportDate
0             2022-08-03 2022-08-03
37            2017-11-02 2017-11-02
40            10/05/2024 2024-05-10
61            2019-02-15 2019-02-15
76            01/04/2022 2022-04-01
89            2024-08-30 2024-08-30
187           2024-08-05 2024-08-05
214  2019-06-25 00:00:00 2019-06-25
220           2019-06-26 2019-06-26
225           28/12/2023 2023-12-28
245           12/04/2022 2022-04-12
259           21/07/2023 2023-07-21
268           2019-07-18 2019-07-18
280           2024-09-06 2024-09-06
309           30/11/2020 2020-11-30
358           08/03/2023 2023-03-08
366           2024-03-28 2024-03-28
376           24/11/2018 2018-11-24
384           2024-04-26 2024-04-26
419           2021-12-27 2021-12-27
429           2024-09-22 2024-09-22
452           2025-03-28 2025-03-28
483           2024-09-13 2024-09-13
502           2024-09-07 2024-09-07
525           2025-03-17 2025-03-17
613           2024-09-05 2024-09-05
641           2024-10-02 2024-10-02
649           2023-10-23 2023-10-23
665           2023-11-10 2023-11-10
676           2020-05-31 2020-05-31
698           2025-06-17 2025-06-17
716           2016-03-31 2016-03-31
722           2025-12-08 2025-12-08
747           2016-11-29 2016-11-29
763           2023-10-03 2023-10-03
780           2021-09-20 2021-09-20
792           2023-06-20 2023-06-20
793           2023-06-06 2023-06-06
802           2025-02-05 2025-02-05

In [50]:
# replace impactSubtype with impactSubType if missing
def replace_impact_subtype(row):
    if pd.isnull(row["impactSubtype"]) and not pd.isnull(row["impactSubType"]):
        row["impactSubtype"] = row["impactSubType"]
    return row
labelled_reports_all = labelled_reports_all.apply(replace_impact_subtype, axis=1)
labelled_reports_all[["impactSubtype", "impactSubType"]].isnull().sum()

impactSubtype      1
impactSubType    599
dtype: int64

In [56]:
labelled_reports_all[labelled_reports_all.impactSubtype.isnull()]

,reportDate,impactSubtype,impactValue,impactUnit,impactValuePrecision,impactValueMin,impactValueMax,annotation,country,location,startYear,startMonth,startDay,endYear,endMonth,endDay,hazards,appealCode,comments,reportDate_orig
766,2023-10-03,NaN,NaN,NaN,NaN,NaN,NaN,[],['Lebanon'],"['Bekaa', 'North']",2023.0,2.0,21.0,2023.0,5.0,30.0,['Cold wave'],MDRLB013,NaN,2023-10-03

In [51]:
labelled_reports_all.drop(columns=["impactSubType"], inplace=True)

In [52]:
labelled_reports_all.columns

Index(['reportDate', 'impactSubtype', 'impactValue', 'impactUnit',
       'impactValuePrecision', 'impactValueMin', 'impactValueMax',
       'annotation', 'country', 'location', 'startYear', 'startMonth',
       'startDay', 'endYear', 'endMonth', 'endDay', 'hazards', 'appealCode',
       'comments', 'reportDate_orig'],
      dtype='object')

In [57]:
labelled_reports_all.to_csv(DATA_LABELLED / f"labelled_reports_all_v{dt.datetime.now().strftime('%d%m%Y')}.csv", index=False)

In [58]:
reload_df = pd.read_csv(DATA_LABELLED / f"labelled_reports_all_v{dt.datetime.now().strftime('%d%m%Y')}.csv")

In [59]:
reload_df.columns

Index(['reportDate', 'impactSubtype', 'impactValue', 'impactUnit',
       'impactValuePrecision', 'impactValueMin', 'impactValueMax',
       'annotation', 'country', 'location', 'startYear', 'startMonth',
       'startDay', 'endYear', 'endMonth', 'endDay', 'hazards', 'appealCode',
       'comments', 'reportDate_orig'],
      dtype='object')